# Gundam Tracking Project

In [1]:
import requests
import pandas as pd
from datetime import datetime

gundam_category = '86'

r = requests.get(f"https://tcgcsv.com/tcgplayer/{gundam_category}/groups")
all_groups = r.json()['results']
product_df = pd.DataFrame()
product_rows = []
price_rows = []

for group in all_groups:
    #Group ID = TCGPlayer's Page (ie. GD01, GD02, ST01)
    group_id = group['groupId']
    r = requests.get(f"https://tcgcsv.com/tcgplayer/{gundam_category}/{group_id}/products")
    products = r.json()['results']

    for product in products:
        # Process product information
        product_row_data = {
            'productId': product['productId'],
            'name': product['name'],
            'cleanName': product['cleanName'],
            'imageUrl': product['imageUrl'],
            'categoryId':product['categoryId'],
            'groupId':product['groupId'],
            'url':product['url'],
            'modifiedOn': product['modifiedOn'],
            'imageCount': product['imageCount'],
            'isPresale':product['presaleInfo'].get('isPresale'),
            'releasedOn':product['presaleInfo'].get('releasedOn'),
        }
        
        #Break down the nested dictionary within the data
        for field in product.get('extendedData',[]): #in another list
            col_name = field['name']
            product_row_data[col_name] = field['value']
        
        product_rows.append(product_row_data)
        #print(f"{product['productId']} - {product['name']}")
        

    r = requests.get(f"https://tcgcsv.com/tcgplayer/{gundam_category}/{group_id}/prices")
    prices = r.json()['results']

    for price in prices:
        # Process prices
        price_row_data = {
            'productId':price['productId'],
            'lowPrice':price['lowPrice'],
            'midPrice':price['midPrice'],
            'highPrice':price['highPrice'],
            'marketPrice':price['marketPrice'],
            'directLowPrice':price['directLowPrice'],
            'subTypeName':price['subTypeName']
        }
        
        price_rows.append(price_row_data)
        #print(f"{price['productId']} - {price['subTypeName']} - {price['midPrice']}")

    #break  (Only process the first group and break for testing)

In [2]:
#Check when was the data was last updated
date_request = requests.get('https://tcgcsv.com/last-updated.txt').text
format_string = '%Y-%m-%dT%H:%M:%S%z'
date = datetime.strptime(date_request, format_string).replace(tzinfo=None).date()
str(date)

'2026-01-29'

In [3]:
#Import scraped data into dataframes for cleaning/exploration
product_df = pd.DataFrame(product_rows)
price_df = pd.DataFrame(price_rows)

In [4]:
#Add the date into both dataframes for tracking
product_df['Date'] = date
price_df['Date'] = date

In [5]:
product_df.head()

,productId,name,cleanName,imageUrl,categoryId,groupId,url,modifiedOn,imageCount,isPresale,...,Description,Level,Cost,CardType,Color,Trait,Link Condition,Attack Points,Hit Points,Date
0,662113,Steel Requiem Booster Pack,Steel Requiem Booster Pack,https://tcgplayer-cdn.tcgplayer.com/product/66...,86,24522,https://www.tcgplayer.com/product/662113/gunda...,2026-01-28T15:30:43.96,1,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
1,662114,Steel Requiem Booster Box,Steel Requiem Booster Box,https://tcgplayer-cdn.tcgplayer.com/product/66...,86,24522,https://www.tcgplayer.com/product/662114/gunda...,2026-01-28T15:30:16.87,1,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
2,662115,Steel Requiem Booster Box Case,Steel Requiem Booster Box Case,https://tcgplayer-cdn.tcgplayer.com/product/66...,86,24522,https://www.tcgplayer.com/product/662115/gunda...,2026-01-28T15:30:28.78,1,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
3,662117,Steel Requiem Sleeved Booster Pack,Steel Requiem Sleeved Booster Pack,https://tcgplayer-cdn.tcgplayer.com/product/66...,86,24522,https://www.tcgplayer.com/product/662117/gunda...,2025-11-04T17:08:09.637,0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
4,670488,Gundam NT-1,Gundam NT 1,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670488/gunda...,2026-01-22T13:55:33.877,1,True,...,"[Repair 2] (At the end of your turn, this Unit...",5,4,Unit,Blue,(Earth Federation),[Christina Mackenzie] / [Amuro Ray],4,4,2026-01-29

In [6]:
price_df.head()

,productId,lowPrice,midPrice,highPrice,marketPrice,directLowPrice,subTypeName,Date
0,662114,138.47,140.90,299.00,135.56,None,Normal,2026-01-29
1,662115,1593.81,1634.35,2099.64,1704.16,None,Normal,2026-01-29
2,670488,18.65,20.00,30.00,18.12,None,Holofoil,2026-01-29
3,670489,20.00,25.00,90.99,24.00,None,Holofoil,2026-01-29
4,670490,0.32,5.50,50.32,0.32,None,Holofoil,2026-01-29

## Data Validation

In [7]:
price_df.isna().any()

productId         False
lowPrice          False
midPrice          False
highPrice         False
marketPrice        True
directLowPrice     True
subTypeName       False
Date              False
dtype: bool

In [8]:
price_df[price_df['marketPrice'].isna()]

,productId,lowPrice,midPrice,highPrice,marketPrice,directLowPrice,subTypeName,Date
7,670493,2.32,3.00,20.32,NaN,None,Holofoil,2026-01-29
8,670494,0.25,0.40,1.00,NaN,None,Normal,2026-01-29
9,670495,0.25,0.40,1.00,NaN,None,Normal,2026-01-29
17,670503,0.25,0.40,1.00,NaN,None,Normal,2026-01-29
23,670509,0.50,1.50,2.00,NaN,None,Normal,2026-01-29
24,670510,1.50,3.25,5.00,NaN,None,Normal,2026-01-29
25,670511,0.25,0.40,1.00,NaN,None,Normal,2026-01-29
26,670512,0.25,0.40,1.00,NaN,None,Normal,2026-01-29
32,670518,0.25,0.33,0.40,NaN,None,Normal,2026-01-29
36,670522,2.32,7.51,20.32,NaN,None,Holofoil,2026-01-29
39,670525,0.50,1.00,1.50,NaN,None,Normal,2026-01-29
54,670540,0.50,1.00,1.50,NaN,None,Normal,2026-01-29
59,670545,0.32,6.75,20.32,NaN,None,Holofoil,2026-01-29
62,670548,0.25,0.33,0.40,NaN,None,Normal,2026-01-29
63,670549,0.25,0.40,1.00,NaN,None,Normal,2026-01-29
64,670550,5.00,23.01,25.00,NaN,None,Normal,2026-01-29
65,673452,0.50,1.50,3.00,NaN,None,Normal,2026-01-29
74,673461,0.40,0.50,1.00,NaN,None,Normal,2026-01-29
81,673468,0.32,5.50,21.00,NaN,None,Holofoil,2026-01-29
83,673470,0.50,1.00,1.50,NaN,None,Normal,2026-01-29
85,673472,0.25,0.40,3.00,NaN,None,Normal,2026-01-29
95,673482,0.50,1.00,1.50,NaN,None,Normal,2026-01-29
115,673502,0.25,0.40,1.00,NaN,None,Normal,2026-01-29
118,673505,0.50,1.50,2.00,NaN,None,Normal,2026-01-29
122,673509,0.50,1.00,1.50,NaN,None,Normal,2026-01-29
123,673510,0.50,1.00,1.50,NaN,None,Normal,2026-01-29
124,673511,0.25,0.33,0.40,NaN,None,Normal,2026-01-29
130,673517,0.25,0.33,0.40,NaN,None,Normal,2026-01-29
132,673519,0.25,0.33,0.40,NaN,None,Normal,2026-01-29
133,673520,0.32,5.50,20.32,NaN,None,Holofoil,2026-01-29
145,673532,2.00,2.00,2.00,NaN,None,Normal,2026-01-29
149,673536,2.00,2.00,2.00,NaN,None,Normal,2026-01-29
150,673537,2.00,2.00,2.00,NaN,None,Normal,2026-01-29
186,672972,24.99,24.99,24.99,NaN,None,Normal,2026-01-29
221,672971,21.99,23.49,24.99,NaN,None,Normal,2026-01-29
447,670920,22.99,22.99,22.99,NaN,None,Normal,2026-01-29
756,619164,379.99,379.99,379.99,NaN,None,Normal,2026-01-29
793,619179,374.98,374.98,374.98,NaN,None,Normal,2026-01-29
794,619180,850.00,850.00,850.00,NaN,None,Normal,2026-01-29
856,654139,15000.00,15000.00,15000.00,NaN,None,Holofoil,2026-01-29
915,670593,60.00,60.00,60.00,NaN,None,Holofoil,2026-01-29
916,670594,80.00,80.00,80.00,NaN,None,Holofoil,2026-01-29
921,671158,29.99,29.99,29.99,NaN,None,Normal,2026-01-29

In [9]:
#Get the ProductIDs of those missing a Market Price
missing_mp_list = []
for item in price_df[price_df['marketPrice'].isna()]['productId']:
    missing_mp_list.append(item)

In [10]:
product_df[product_df['productId'].isin(missing_mp_list) == True]

,productId,name,cleanName,imageUrl,categoryId,groupId,url,modifiedOn,imageCount,isPresale,...,Description,Level,Cost,CardType,Color,Trait,Link Condition,Attack Points,Hit Points,Date
9,670493,Penelope (Middle Form),Penelope Middle Form,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670493/gunda...,2025-12-24T20:07:36.657,1,True,...,[Deploy] Choose 1 to 2 enemy Units with 3 or l...,6,5,Unit,Blue,(Earth Federation),[Lane Aim],4,4,2026-01-29
10,670494,Hizack Custom,Hizack Custom,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670494/gunda...,2026-01-22T13:58:42.09,1,True,...,While you have 2 or more (Titans) Units in pla...,3,2,Unit,Blue,(Titans),NaN,3,2,2026-01-29
11,670495,Baund Doc,Baund Doc,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670495/gunda...,2025-12-24T20:07:48.96,1,True,...,[Activate: Main] [Once per Turn] Exile 3 (Tita...,6,5,Unit,Blue,(Titans),[Jerid Messa],4,5,2026-01-29
19,670503,Auda's Maganac,Audas Maganac,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670503/gunda...,2025-12-24T20:09:57.883,1,True,...,"[Attack] If you are attacking an enemy Unit, t...",3,2,Unit,Green,(Maganac Corps),(Maganac Corps) Trait,2,3,2026-01-29
25,670509,Patulia,Patulia,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670509/gunda...,2025-12-24T20:10:38.167,1,True,...,[Deploy] Deal 3 damage to all Bases.,7,6,Unit,Red,(SRA),[Carris Nautilus],5,6,2026-01-29
26,670510,Duel Gundam (Assault Shroud) (GD03-042),Duel Gundam Assault Shroud GD03 042,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670510/gunda...,2025-12-24T20:10:43.59,1,True,...,"While this Unit has 5 or more AP, it may choos...",5,3,Unit,Red,(ZAFT),[Yzak Joule],3,4,2026-01-29
27,670511,Daughtress Flyer,Daughtress Flyer,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670511/gunda...,2025-12-24T20:10:49.213,1,True,...,[Deploy] Deploy 1 rested [Daughtress]((New UNE...,3,2,Unit,Red,(New UNE),NaN,2,3,2026-01-29
28,670512,Balient,Balient,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670512/gunda...,2025-12-24T20:10:57.177,1,True,...,"While you have a Unit token in play, this Unit...",3,2,Unit,Red,(New UNE),NaN,2,4,2026-01-29
34,670518,Defurse,Defurse,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670518/gunda...,2025-12-24T20:11:44.183,1,True,...,[Deploy] You may 1 (X-Rounder) card from your ...,5,4,Unit,Purple,(UE) (Vagan),NaN,2,5,2026-01-29
38,670522,Aile Strike Gundam,Aile Strike Gundam,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670522/gunda...,2025-12-24T20:12:11.457,1,True,...,[Blocker] (Rest this Unit to change the attack...,4,3,Unit,White,(Triple Ship Alliance),[Mu La Flaga],3,4,2026-01-29
41,670525,Freedom Gundam (Meteor),Freedom Gundam Meteor,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670525/gunda...,2026-01-22T13:51:05.003,1,True,...,"[Once per Turn] During your turn, when your (T...",8,6,Unit,White,(Triple Ship Alliance),[Kira Yamato],6,6,2026-01-29
56,670540,Eliminate Target,Eliminate Target,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670540/gunda...,2026-01-22T13:50:37.78,1,True,...,[Main] / [Action] Choose 1 Pilot paired with a...,6,1,Command,Red,NaN,NaN,NaN,NaN,2026-01-29
61,670545,Awakened Potential,Awakened Potential,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670545/gunda...,2025-12-24T20:15:16.587,1,True,...,[Burst] Add this card to your hand.<br>\r\n[Ac...,4,1,Command,White,NaN,NaN,NaN,NaN,2026-01-29
64,670548,Unheralded Attack,Unheralded Attack,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670548/gunda...,2025-12-24T20:15:34.893,1,True,...,[Action] Choose 1 friendly Base and 1 enemy Un...,1,1,Command,White,(AEUG) (Newtype),NaN,+1,0,2026-01-29
65,670549,Cyclops Team,Cyclops Team,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670549/gunda...,2025-12-24T20:15:42.077,1,True,...,[Burst] Deploy this card.<br>\r\n[Deploy] Add ...,4,1,Base,Green,(Zeon) (Cyclops Team),NaN,0,5,2026-01-29
66,670550,Ad Balloon,Ad Balloon,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/670550/gunda...,2025-12-24T20:15:48.73,1,True,...,This Unit can't be set as active or paired wit...,NaN,NaN,Unit,NaN,(Civilian),NaN,0,1,2026-01-29
67,673452,Gundam NT-1 Full Armor,Gundam NT 1 Full Armor,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673452/gunda...,2026-01-22T13:55:38.78,1,True,...,[Destroyed] Choose 1 enemy Unit with 3 or less...,3,2,Unit,Blue,(Earth Federation),[Christina Mackenzie] / [Amuro Ray],2,3,2026-01-29
76,673461,Hy-Gogg,Hy Gogg,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673461/gunda...,2026-01-22T13:59:18.637,1,True,...,[When Linked] If you have another (Cyclops Tea...,3,2,Unit,Green,(Zeon) (Cyclops Team),(Cyclops Team) Trait,3,2,2026-01-29
83,673468,Bertigo,Bertigo,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673468/gunda...,2026-01-21T22:08:46.263,1,True,...,"[During Link] During your turn, while this Uni...",5,4,Unit,Red,(SRA),(Newtype) Trait,4,4,2026-01-29
85,673470,Gundam Virsago & Gundam Ashtaron,Gundam Virsago and Gundam Ashtaron,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673470/gunda...,2026-01-22T13:56:25.637,1,True,...,[During Link] This Unit gains [High-Maneuver>....,5,3,Unit,Red,(New UNE),[Shagia Frost] / [Olba Frost],3,5,2026-01-29
87,673472,CGUE,CGUE,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673472/gunda...,2026-01-21T22:08:46.513,1,True,...,NaN,2,2,Unit,Red,(ZAFT),NaN,2,3,2026-01-29
97,673482,Farsia,Farsia,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673482/gunda...,2026-01-22T13:50:50.757,1,True,...,This card in your trash gets cost -1.,2,2,Unit,Purple,(UE) (Vagan),[Yurin L'Ciel],2,2,2026-01-29
117,673502,Privileged Position,Privileged Position,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673502/gunda...,2026-01-21T22:08:49.57,1,True,...,[Burst] Draw 1.<br>\n[Action] Choose 1 of your...,6,2,Command,Blue,NaN,NaN,NaN,NaN,2026-01-29
120,673505,M.A.V. Tactics,MAV Tactics,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673505/gunda...,2026-01-22T14:02:54.507,1,True,...,[Main] Deploy 1 rested [GQuuuuuuX (Omega Psyco...,6,4,Command,Green,NaN,NaN,NaN,NaN,2026-01-29
124,673509,Infiltrator Present,Infiltrator Present,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673509/gunda...,2026-01-22T14:00:49.527,1,True,...,[Main] / [Action] Choose 1 friendly (Mafty) Un...,3,1,Command,Red,(Mafty),NaN,0,+1,2026-01-29
125,673510,Distant Reunion,Distant Reunion,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673510/gunda...,2026-01-21T22:08:50.52,1,True,...,[Action] Choose 1 friendly Unit paired with an...,3,1,Command,Purple,(Civilian) (Vagan) (X-Rounder),NaN,+1,0,2026-01-29
126,673511,Towards Destiny,Towards Destiny,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673511/gunda...,2026-01-21T22:08:50.63,1,True,...,[Main] / [Action] Choose 1 friendly (Vagan) Un...,3,1,Command,Purple,NaN,NaN,NaN,NaN,2026-01-29
132,673517,Doritea,Doritea,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673517/gunda...,2026-01-22T17:18:38.927,1,True,...,[Burst] Deploy this card.<br>\r\n[Deploy] Add ...,4,1,Base,Red,(New UNE) (Warship),NaN,0,5,2026-01-29
134,673519,Downes,Downes,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673519/gunda...,2026-01-21T22:08:51.86,1,True,...,[Burst] Deploy this card.<br>\n[Deploy] Add 1 ...,5,2,Base,Purple,(Vagan) (Stronghold),NaN,0,5,2026-01-29
135,673520,Eternal,Eternal,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673520/gunda...,2026-01-22T13:50:46.82,1,True,...,[Burst] Deploy this card.<br>\r\n[Deploy] Add ...,5,2,Base,White,(Triple Ship Alliance) (Warship),NaN,0,5,2026-01-29
147,673532,Hy-Gogg (T-013),Hy Gogg T 013,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673532/gunda...,2026-01-22T13:59:24.257,1,True,...,NaN,NaN,NaN,Unit,NaN,(Zeon),NaN,2,1,2026-01-29
151,673536,Red Gundam (T-018),Red Gundam T 018,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673536/gunda...,2026-01-21T22:08:53.603,1,True,...,NaN,NaN,NaN,Unit,NaN,(Clan),NaN,2,3,2026-01-29
152,673537,GQuuuuuuX (Omega Psycommu) (T-019),GQuuuuuuX Omega Psycommu T 019,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/673537/gunda...,2026-01-22T13:52:55.867,1,True,...,NaN,NaN,NaN,Unit,NaN,(Clan),NaN,3,2,2026-01-29
239,672972,Starter Deck: Celestial Drive Bonus Pack,Starter Deck Celestial Drive Bonus Pack,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24410,https://www.tcgplayer.com/product/672972/gunda...,2026-01-20T15:26:03.017,0,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
275,672971,Starter Deck: Flash of Radiance Bonus Pack,Starter Deck Flash of Radiance Bonus Pack,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24411,https://www.tcgplayer.com/product/672971/gunda...,2026-01-20T15:25:23.523,0,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
502,670920,Starter Deck: Clan Unity Bonus Pack,Starter Deck Clan Unity Bonus Pack,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24409,https://www.tcgplayer.com/product/670920/gunda...,2026-01-05T13:43:15.58,0,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
818,619164,Starter Deck 03: Zeon's Rush - Gundam Assemble...,Starter Deck 03 Zeons Rush Gundam Assemble Sta...,https://tcgplayer-cdn.tcgplayer.com/product/61...,86,24224,https://www.tcgplayer.com/product/619164/gunda...,2025-07-11T04:10:19.4,1,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
857,619179,Starter Deck 04: SEED Strike - Gundam Assemble...,Starter Deck 04 SEED Strike Gundam Assemble St...,https://tcgplayer-cdn.tcgplayer.com/product/61...,86,24225,https://www.tcgplayer.com/product/619179/gunda...,2025-07-11T04:10:19.65,1,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
858,619180,Starter Deck 04: SEED Strike - Gundam Assemble...,Starter Deck 04 SEED Strike Gundam Assemble St...,https://tcgplayer-cdn.tcgplayer.com/product/61...,86,24225,https://www.tcgplayer.com/product/619180/gunda...,2025-07-11T04:10:19.65,1,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
920,654139,Wing Gundam Zero (Championship Winner Card 01),Wing Gundam Zero Championship Winner Card 01,https://tcgplayer-cdn.tcgplayer.com/product/65...,86,24340,https://www.tcgplayer.com/product/654139/gunda...,2025-09-23T20:47:34.223,1,False,...,<High-Maneuver> (This Unit can't be blocked.)<...,8,8,Unit,Green,(G Team),[Heero Yuy],5,7,2026-01-29
982,670593,GQuuuuuuX (Omega Psycommu) (Premium Card Colle...,GQuuuuuuX Omega Psycommu Premium Card Collection,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24340,https://www.tcgplayer.com/product/670593/gunda...,2026-01-05T20:09:43.74,1,False,...,[Deploy] If another friendly (Clan) Unit is in...,4,3,Unit,Red,(Clan),[Amate Yuzuriha (Machu)],4,2,2026-01-29
983,670594,Perfect Strike Gundam (Premium Card Collection),Perfect Strike Gundam Premium Card Collection,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24340,https://www.tcgplayer.com/product/670594/gunda...,2026-01-05T20:09:57.463,1,False,...,<Blocker> (Rest this Unit to change the attack...,5,3,Unit,White,(Triple Ship Alliance),(Earth Alliance) Trait,4,4,2026-01-29
990,671158,Store Tournament Winner Pack 03,Store Tournament Winner Pack 03,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24340,https://www.tcgplayer.com/product/671158/gunda...,2026-01-06T18:01:03.167,1,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29

<div class="alert alert-block alert-info">
    The products currently listed at the time of writing <b>(01/27)</b> are negligible. Some examples of the products listed are "Bonus Packs", which is a single holofoil card that comes with the purchase of each structure deck. The pack themselves are typically not sold individually, which explains why there is no set market price for them. The other examples include the "Premium Card Collection", which are exclusive to the Bandai Regional Card Fest event. Given the exclusivity of these cards, on top of needing to be selected via a lottery to purchase the collection, there is no set market for this card quite yet.
 
</div>

In [11]:
price_df['directLowPrice'].value_counts()

Series([], Name: directLowPrice, dtype: int64)

<div class="alert alert-block alert-info">
    Nulls and missing values are true in the <b>"marketPrice" and "directLowPrice"</b> column.
<br> 
    
This is to be expected given that TCGPlayer differentiates their own pricing:
* {directLowPrice} is the lowest price for a card in the TCGPlayer warehouse.
* {lowPrice} is the lowest price from any independent seller in the marketplace.

For Gundam TCG specifically, TCGPlayer **does not** directly sell any Gundam cards, leading to the null values that we have now.

In [12]:
product_df.isnull().any()

productId         False
name              False
cleanName         False
imageUrl          False
categoryId        False
groupId           False
url               False
modifiedOn        False
imageCount        False
isPresale         False
releasedOn         True
Rarity             True
Number             True
Description        True
Level              True
Cost               True
CardType           True
Color              True
Trait              True
Link Condition     True
Attack Points      True
Hit Points         True
Date              False
dtype: bool

In [13]:
product_df[product_df['Rarity'].isnull() == True]

,productId,name,cleanName,imageUrl,categoryId,groupId,url,modifiedOn,imageCount,isPresale,...,Description,Level,Cost,CardType,Color,Trait,Link Condition,Attack Points,Hit Points,Date
0,662113,Steel Requiem Booster Pack,Steel Requiem Booster Pack,https://tcgplayer-cdn.tcgplayer.com/product/66...,86,24522,https://www.tcgplayer.com/product/662113/gunda...,2026-01-28T15:30:43.96,1,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
1,662114,Steel Requiem Booster Box,Steel Requiem Booster Box,https://tcgplayer-cdn.tcgplayer.com/product/66...,86,24522,https://www.tcgplayer.com/product/662114/gunda...,2026-01-28T15:30:16.87,1,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
2,662115,Steel Requiem Booster Box Case,Steel Requiem Booster Box Case,https://tcgplayer-cdn.tcgplayer.com/product/66...,86,24522,https://www.tcgplayer.com/product/662115/gunda...,2026-01-28T15:30:28.78,1,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
3,662117,Steel Requiem Sleeved Booster Pack,Steel Requiem Sleeved Booster Pack,https://tcgplayer-cdn.tcgplayer.com/product/66...,86,24522,https://www.tcgplayer.com/product/662117/gunda...,2025-11-04T17:08:09.637,0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
201,675730,Battle of Aces (SP) (R+),Battle of Aces SP Rplus,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/675730/gunda...,2026-01-29T19:50:01.367,0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,671153,Store Tournament Winner Pack 02,Store Tournament Winner Pack 02,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24340,https://www.tcgplayer.com/product/671153/gunda...,2026-01-06T17:59:32.34,0,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
989,671155,Store Tournament Participation Pack 03,Store Tournament Participation Pack 03,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24340,https://www.tcgplayer.com/product/671155/gunda...,2026-01-06T18:00:15.723,1,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
990,671158,Store Tournament Winner Pack 03,Store Tournament Winner Pack 03,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24340,https://www.tcgplayer.com/product/671158/gunda...,2026-01-06T18:01:03.167,1,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
1114,617436,Gundam Card Game Edition Beta Box,Gundam Card Game Edition Beta Box,https://tcgplayer-cdn.tcgplayer.com/product/61...,86,24193,https://www.tcgplayer.com/product/617436/gunda...,2025-02-07T19:03:43.763,1,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29
1115,617437,Gundam Card Game Edition Beta Pack,Gundam Card Game Edition Beta Pack,https://tcgplayer-cdn.tcgplayer.com/product/61...,86,24193,https://www.tcgplayer.com/product/617437/gunda...,2025-02-07T19:05:43.287,1,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-29

## Data Transformation

In [14]:
price_df.shape

(1045, 8)

In [15]:
product_df.shape

(1116, 23)

In [16]:
#Join the data for easier viewing
df = pd.merge(product_df,price_df,how='left',left_on='productId', right_on='productId')

<div class="alert alert-block alert-info">
    <b> As of January 27th, </b> the Product_df has more data rows as a result of having active "Product Display Pages" (PDP) for the GD03 Booster Set. As this set is due to be released on Friday, January 30th, there is no active pricing data to join to the product information, leading to the null values seen in the columns joined from the pricing_df. 
    
> __For future proofing of this project, a left join will be conducted rather than an inner to enable us to still actively view card details.__
 
</div>

In [17]:
df.shape

(1117, 30)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1117 entries, 0 to 1116
Data columns (total 30 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   productId       1117 non-null   int64
 1   name            1117 non-null   object
 2   cleanName       1117 non-null   object
 3   imageUrl        1117 non-null   object
 4   categoryId      1117 non-null   int64
 5   groupId         1117 non-null   int64
 6   url             1117 non-null   object
 7   modifiedOn      1117 non-null   object
 8   imageCount      1117 non-null   int64
 9   isPresale       1117 non-null   bool
 10  releasedOn      724 non-null    object
 11  Rarity          1046 non-null   object
 12  Number          1046 non-null   object
 13  Description     902 non-null    object
 14  Level           918 non-null    object
 15  Cost            918 non-null    object
 16  CardType        1043 non-null   object
 17  Color           918 non-null    object
 18  Trait           832 non-null    object
 19  Link Condition  427 non-null    object
 20  Attack Points   846 non-null    object
 21  Hit Points      846 non-null    object
 22  Date_x          1117 non-null   object
 23  lowPrice        1045 non-null   float64
 24  midPrice        1045 non-null   float64
 25  highPrice       1045 non-null   float64
 26  marketPrice     1002 non-null   float64
 27  directLowPrice  0 non-null      object
 28  subTypeName     1045 non-null   object
 29  Date_y          1045 non-null   object
dtypes: bool(1), float64(4), int64(4), object(21)
memory usage: 262.9+ KB

In [19]:
df.isnull().any()

productId         False
name              False
cleanName         False
imageUrl          False
categoryId        False
groupId           False
url               False
modifiedOn        False
imageCount        False
isPresale         False
releasedOn         True
Rarity             True
Number             True
Description        True
Level              True
Cost               True
CardType           True
Color              True
Trait              True
Link Condition     True
Attack Points      True
Hit Points         True
Date_x            False
lowPrice           True
midPrice           True
highPrice          True
marketPrice        True
directLowPrice     True
subTypeName        True
Date_y             True
dtype: bool

<alert alert-block alert-info>

In [20]:
df[df['lowPrice'].isnull() == True]

,productId,name,cleanName,imageUrl,categoryId,groupId,url,modifiedOn,imageCount,isPresale,...,Attack Points,Hit Points,Date_x,lowPrice,midPrice,highPrice,marketPrice,directLowPrice,subTypeName,Date_y
0,662113,Steel Requiem Booster Pack,Steel Requiem Booster Pack,https://tcgplayer-cdn.tcgplayer.com/product/66...,86,24522,https://www.tcgplayer.com/product/662113/gunda...,2026-01-28T15:30:43.96,1,True,...,NaN,NaN,2026-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,662117,Steel Requiem Sleeved Booster Pack,Steel Requiem Sleeved Booster Pack,https://tcgplayer-cdn.tcgplayer.com/product/66...,86,24522,https://www.tcgplayer.com/product/662117/gunda...,2025-11-04T17:08:09.637,0,True,...,NaN,NaN,2026-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,675678,A Healthy Curiosity (R+),A Healthy Curiosity Rplus,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/675678/gunda...,2026-01-29T18:43:26.853,0,True,...,NaN,NaN,2026-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,675679,A Show of Resolve (SP) (U+),A Show of Resolve SP Uplus,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/675679/gunda...,2026-01-29T18:43:26.9,0,True,...,NaN,NaN,2026-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,675680,Altron Gundam (LR+),Altron Gundam LRplus,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24522,https://www.tcgplayer.com/product/675680/gunda...,2026-01-29T18:43:26.95,0,True,...,5,6,2026-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,670595,Gundam Lfrith (Premium Card Collection),Gundam Lfrith Premium Card Collection,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24340,https://www.tcgplayer.com/product/670595/gunda...,2026-01-05T20:09:50.227,1,False,...,2,4,2026-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
985,670968,Premium Card Collection 01 [EVX05],Premium Card Collection 01 EVX05,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24340,https://www.tcgplayer.com/product/670968/gunda...,2026-01-05T20:18:03.993,1,False,...,NaN,NaN,2026-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,675653,Zaku II FZ (GD03 Release Event),Zaku II FZ GD03 Release Event,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24340,https://www.tcgplayer.com/product/675653/gunda...,2026-01-29T16:17:50.93,1,False,...,NaN,NaN,2026-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,675654,Bernard Wiseman (GD03 Release Event),Bernard Wiseman GD03 Release Event,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,24340,https://www.tcgplayer.com/product/675654/gunda...,2026-01-29T16:18:56.987,1,False,...,NaN,NaN,2026-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1085,616650,Gundam Aerial (R+),Gundam Aerial Rplus,https://tcgplayer-cdn.tcgplayer.com/product/61...,86,24193,https://www.tcgplayer.com/product/616650/gunda...,2025-07-23T13:57:56.933,1,False,...,3,3,2026-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
#Clean up HTML formatting from text
remove_strings = ['<br>','\r','\n']
for i in df['Description']:
    for string in remove_strings:
        df['Description'] = df['Description'].str.replace(string,' ')

In [22]:
df[['name','Description']]

,name,Description
0,Steel Requiem Booster Pack,NaN
1,Steel Requiem Booster Box,NaN
2,Steel Requiem Booster Box Case,NaN
3,Steel Requiem Sleeved Booster Pack,NaN
4,Gundam NT-1,"[Repair 2] (At the end of your turn, this Unit..."
...,...,...
1112,Resource (C+),(Rest a Resource when paying a cost.)
1113,EX Base,"(At the start of the game, place 1 active EX B..."
1114,EX Resource,"(At the start of the game, the second-turn pla..."
1115,Gundam Card Game Edition Beta Box,NaN
1116,Gundam Card Game Edition Beta Pack,NaN

In [23]:
#Rename columns for easier readability
df.rename(columns = {
    'groupId':'Set',
    'subTypeName':'Holofoil',
    'Date_x':'Date'
},inplace=True)

In [24]:
set_dict = {
    24193:'Edition Beta',
    24221: 'Newtype Rising (GD01)',
    24222: 'Starter Deck 01: Heroic Beginnings (ST01)',
    24223: 'Starter Deck 02: Wings of Advance (ST02)',
    24224: 'Starter Deck 03: Zeon\'s Rush (ST03)',
    24225: 'Starter Deck 04: SEED Strike (ST04)',
    24340: 'Gundam Promotional Cards',
    24372: 'Promotional Resource Tokens',
    24373: 'Promotional EX Resource Tokens',
    24374: 'Promotional EX Base Tokens',
    24407: 'Starter Deck 05: Iron Bloom (ST05)',
    24408: 'Dual Impact (GD02)',
    24409: 'Starter Deck 06: Clan Unity (ST06)',
    24410: 'Starter Deck 07: Celestial Drive (ST07)',
    24411: 'Starter Deck 08: Flash of Radiance (ST08)',
    24522: 'Steel Requiem (GD03)',
}

#alternative
#df['Set'] = df['Set'].replace(set_dict) 

for x,y in set_dict.items():
    df.loc[df['Set'] == x,'Set'] = y
    
df['Set'].value_counts()

Steel Requiem (GD03)                         204
Newtype Rising (GD01)                        197
Dual Impact (GD02)                           191
Gundam Promotional Cards                     105
Edition Beta                                  85
Starter Deck 01: Heroic Beginnings (ST01)     39
Starter Deck 02: Wings of Advance (ST02)      39
Starter Deck 03: Zeon's Rush (ST03)           39
Starter Deck 04: SEED Strike (ST04)           39
Starter Deck 07: Celestial Drive (ST07)       36
Starter Deck 08: Flash of Radiance (ST08)     36
Starter Deck 06: Clan Unity (ST06)            36
Starter Deck 05: Iron Bloom (ST05)            36
Promotional Resource Tokens                   21
Promotional EX Base Tokens                    11
Promotional EX Resource Tokens                 3
Name: Set, dtype: int64

In [25]:
#Export today's data to a CSV and proceed to exploration!
df.to_csv(f'Gundam TCG Pricing Raw Data/gundam_pricing_{str(date)}.csv',index=False)

In [26]:
#Add data to the master csv for storage
import glob
import os
all_files = glob.glob(os.path.join('Gundam TCG Pricing Raw Data', "gundam_pricing*.csv"))
csv_list = []
for csv in all_files:
    read = pd.read_csv(csv)
    csv_list.append(read)

combined_csvs = pd.concat(csv_list,ignore_index=True)
combined_csvs.to_csv('Gundam TCG Pricing Raw Data/master_pricing.csv',index=False)

In [27]:
check = pd.read_csv('Gundam TCG Pricing Raw Data/master_pricing.csv')
check.isnull().any()

productId         False
name              False
cleanName         False
imageUrl          False
categoryId        False
Set               False
url               False
modifiedOn        False
imageCount        False
isPresale         False
releasedOn         True
Rarity             True
Number             True
Description        True
Level              True
Cost               True
CardType           True
Color              True
Trait              True
Link Condition     True
Attack Points      True
Hit Points         True
Date              False
lowPrice           True
midPrice           True
highPrice          True
marketPrice        True
directLowPrice     True
Holofoil           True
Date_y             True
dtype: bool

# Data Exploration

In [28]:
#Expand Rows for viewing
pd.set_option('display.max.rows', None)

In [29]:
df[df['Set'].str.contains('Steel Requiem')]

,productId,name,cleanName,imageUrl,categoryId,Set,url,modifiedOn,imageCount,isPresale,...,Attack Points,Hit Points,Date,lowPrice,midPrice,highPrice,marketPrice,directLowPrice,Holofoil,Date_y
0,662113,Steel Requiem Booster Pack,Steel Requiem Booster Pack,https://tcgplayer-cdn.tcgplayer.com/product/66...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/662113/gunda...,2026-01-28T15:30:43.96,1,True,...,NaN,NaN,2026-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,662114,Steel Requiem Booster Box,Steel Requiem Booster Box,https://tcgplayer-cdn.tcgplayer.com/product/66...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/662114/gunda...,2026-01-28T15:30:16.87,1,True,...,NaN,NaN,2026-01-29,138.47,140.90,299.00,135.56,None,Normal,2026-01-29
2,662115,Steel Requiem Booster Box Case,Steel Requiem Booster Box Case,https://tcgplayer-cdn.tcgplayer.com/product/66...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/662115/gunda...,2026-01-28T15:30:28.78,1,True,...,NaN,NaN,2026-01-29,1593.81,1634.35,2099.64,1704.16,None,Normal,2026-01-29
3,662117,Steel Requiem Sleeved Booster Pack,Steel Requiem Sleeved Booster Pack,https://tcgplayer-cdn.tcgplayer.com/product/66...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/662117/gunda...,2025-11-04T17:08:09.637,0,True,...,NaN,NaN,2026-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,670488,Gundam NT-1,Gundam NT 1,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670488/gunda...,2026-01-22T13:55:33.877,1,True,...,4,4,2026-01-29,18.65,20.00,30.00,18.12,None,Holofoil,2026-01-29
5,670489,The-O,The O,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670489/gunda...,2025-12-24T20:07:10.957,1,True,...,5,5,2026-01-29,20.00,25.00,90.99,24.00,None,Holofoil,2026-01-29
6,670490,Messala,Messala,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670490/gunda...,2026-01-22T14:03:01.83,1,True,...,5,4,2026-01-29,0.32,5.50,50.32,0.32,None,Holofoil,2026-01-29
7,670491,Hambrabi,Hambrabi,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670491/gunda...,2026-01-22T13:58:15.99,1,True,...,5,4,2026-01-29,1.32,3.50,8.00,1.32,None,Holofoil,2026-01-29
8,670492,Kshatriya Besserung,Kshatriya Besserung,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670492/gunda...,2026-01-22T14:02:46.58,1,True,...,4,4,2026-01-29,1.00,5.50,20.32,1.00,None,Holofoil,2026-01-29
9,670493,Penelope (Middle Form),Penelope Middle Form,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670493/gunda...,2025-12-24T20:07:36.657,1,True,...,4,4,2026-01-29,2.32,3.00,20.32,NaN,None,Holofoil,2026-01-29
10,670494,Hizack Custom,Hizack Custom,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670494/gunda...,2026-01-22T13:58:42.09,1,True,...,3,2,2026-01-29,0.25,0.40,1.00,NaN,None,Normal,2026-01-29
11,670495,Baund Doc,Baund Doc,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670495/gunda...,2025-12-24T20:07:48.96,1,True,...,4,5,2026-01-29,0.25,0.40,1.00,NaN,None,Normal,2026-01-29
12,670496,Full Armor Unicorn Gundam (Unicorn Mode),Full Armor Unicorn Gundam Unicorn Mode,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670496/gunda...,2026-01-22T13:51:23.837,1,True,...,5,4,2026-01-29,0.25,0.38,0.50,0.40,None,Normal,2026-01-29
13,670497,Altron Gundam,Altron Gundam,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670497/gunda...,2025-12-24T20:08:01.253,1,True,...,5,6,2026-01-29,23.68,33.00,35.00,27.56,None,Holofoil,2026-01-29
14,670498,Zaku II FZ,Zaku II FZ,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670498/gunda...,2025-12-24T20:08:11.683,1,True,...,1,2,2026-01-29,2.32,3.50,20.32,2.32,None,Holofoil,2026-01-29
15,670499,Gundam Deathscythe Hell,Gundam Deathscythe Hell,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670499/gunda...,2026-01-22T13:54:08.36,1,True,...,6,5,2026-01-29,2.50,10.00,20.32,4.40,None,Holofoil,2026-01-29
16,670500,Gundam Kyrios,Gundam Kyrios,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670500/gunda...,2026-01-22T13:55:22.423,1,True,...,5,3,2026-01-29,1.00,10.00,20.32,3.25,None,Holofoil,2026-01-29
17,670501,G-Bouncer,G Bouncer,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670501/gunda...,2026-01-22T13:51:43.347,1,True,...,4,3,2026-01-29,1.00,5.50,20.32,1.00,None,Holofoil,2026-01-29
18,670502,Gundam Sandrock Custom,Gundam Sandrock Custom,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670502/gunda...,2026-01-22T13:55:42.74,1,True,...,5,4,2026-01-29,0.50,1.05,1.60,1.50,None,Normal,2026-01-29
19,670503,Auda's Maganac,Audas Maganac,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670503/gunda...,2025-12-24T20:09:57.883,1,True,...,2,3,2026-01-29,0.25,0.40,1.00,NaN,None,Normal,2026-01-29
20,670504,Gundam Kyrios (Tail Unit Flight Mode),Gundam Kyrios Tail Unit Flight Mode,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670504/gunda...,2026-01-22T13:55:29.053,1,True,...,3,4,2026-01-29,0.25,0.33,0.40,0.25,None,Normal,2026-01-29
21,670505,Gundam AGE-1 Flat,Gundam AGE 1 Flat,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670505/gunda...,2026-01-22T13:53:27.403,1,True,...,4,3,2026-01-29,0.25,0.40,1.00,0.25,None,Normal,2026-01-29
22,670506,GFreD,GFreD,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670506/gunda...,2026-01-22T13:51:55.91,1,True,...,4,5,2026-01-29,13.68,44.45,90.99,14.34,None,Holofoil,2026-01-29
23,670507,Xi Gundam (Flight Form),Xi Gundam Flight Form,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670507/gunda...,2025-12-24T20:10:24.597,1,True,...,4,4,2026-01-29,2.32,6.50,20.32,2.32,None,Holofoil,2026-01-29
24,670508,Red Gundam,Red Gundam,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670508/gunda...,2025-12-24T20:10:31.553,1,True,...,2,4,2026-01-29,1.00,5.50,20.32,1.00,None,Holofoil,2026-01-29
25,670509,Patulia,Patulia,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670509/gunda...,2025-12-24T20:10:38.167,1,True,...,5,6,2026-01-29,0.50,1.50,2.00,NaN,None,Normal,2026-01-29
26,670510,Duel Gundam (Assault Shroud) (GD03-042),Duel Gundam Assault Shroud GD03 042,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670510/gunda...,2025-12-24T20:10:43.59,1,True,...,3,4,2026-01-29,1.50,3.25,5.00,NaN,None,Normal,2026-01-29
27,670511,Daughtress Flyer,Daughtress Flyer,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670511/gunda...,2025-12-24T20:10:49.213,1,True,...,2,3,2026-01-29,0.25,0.40,1.00,NaN,None,Normal,2026-01-29
28,670512,Balient,Balient,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670512/gunda...,2025-12-24T20:10:57.177,1,True,...,2,4,2026-01-29,0.25,0.40,1.00,NaN,None,Normal,2026-01-29
29,670513,Gundam Exia (Trans-Am),Gundam Exia Trans Am,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670513/gunda...,2026-01-22T13:54:17.72,1,True,...,6,4,2026-01-29,34.67,35.50,50.00,27.45,None,Holofoil,2026-01-29
30,670514,Gundam Barbatos Lupus,Gundam Barbatos Lupus,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670514/gunda...,2026-01-22T13:54:03.66,1,True,...,5,5,2026-01-29,16.68,24.95,35.00,19.62,None,Holofoil,2026-01-29
31,670515,Zedas R,Zedas R,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670515/gunda...,2025-12-24T20:11:21.287,1,True,...,4,3,2026-01-29,0.50,1.00,1.50,0.50,None,Normal,2026-01-29
32,670516,CGS Mobile Worker (Commander Type),CGS Mobile Worker Commander Type,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670516/gunda...,2025-12-24T20:11:30.38,1,True,...,0,2,2026-01-29,0.50,1.05,1.60,1.50,None,Normal,2026-01-29
33,670517,Gundam Barbatos 6th Form,Gundam Barbatos 6th Form,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670517/gunda...,2026-01-22T13:53:55.83,1,True,...,5,4,2026-01-29,0.50,1.05,1.60,1.50,None,Normal,2026-01-29
34,670518,Defurse,Defurse,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670518/gunda...,2025-12-24T20:11:44.183,1,True,...,2,5,2026-01-29,0.25,0.33,0.40,NaN,None,Normal,2026-01-29
35,670519,Rouei,Rouei,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670519/gunda...,2025-12-24T20:11:50.117,1,True,...,3,4,2026-01-29,0.25,0.38,0.50,0.33,None,Normal,2026-01-29
36,670520,Graham's Union Flag Custom,Grahams Union Flag Custom,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670520/gunda...,2026-01-22T13:53:07.507,1,True,...,4,2,2026-01-29,15.01,44.99,90.99,26.84,None,Holofoil,2026-01-29
37,670521,Freedom Gundam (GD03-070),Freedom Gundam GD03 070,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670521/gunda...,2026-01-22T13:51:00.707,1,True,...,4,5,2026-01-29,23.68,39.99,50.00,23.94,None,Holofoil,2026-01-29
38,670522,Aile Strike Gundam,Aile Strike Gundam,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670522/gunda...,2025-12-24T20:12:11.457,1,True,...,3,4,2026-01-29,2.32,7.51,20.32,NaN,None,Holofoil,2026-01-29
39,670523,Tieren Taozi,Tieren Taozi,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670523/gunda...,2025-12-24T20:12:17.79,1,True,...,3,1,2026-01-29,0.32,5.50,20.32,1.00,None,Holofoil,2026-01-29
40,670524,Super Gundam,Super Gundam,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670524/gunda...,2025-12-24T20:12:24.13,1,True,...,4,4,2026-01-29,0.50,1.05,1.60,1.00,None,Normal,2026-01-29
41,670525,Freedom Gundam (Meteor),Freedom Gundam Meteor,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670525/gunda...,2026-01-22T13:51:05.003,1,True,...,6,6,2026-01-29,0.50,1.00,1.50,NaN,None,Normal,2026-01-29
42,670526,Tieren High Mobility Type,Tieren High Mobility Type,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670526/gunda...,2025-12-24T20:12:35.353,1,True,...,3,1,2026-01-29,0.50,1.00,1.50,0.50,None,Normal,2026-01-29
43,670527,G-Defenser,G Defenser,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670527/gunda...,2026-01-22T13:51:49.423,1,True,...,3,2,2026-01-29,0.25,0.38,0.50,0.30,None,Normal,2026-01-29
44,670528,Gundam Kimaris Trooper (Trooper Mode),Gundam Kimaris Trooper Trooper Mode,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670528/gunda...,2026-01-22T13:55:17.353,1,True,...,5,4,2026-01-29,0.25,0.33,0.40,0.25,None,Normal,2026-01-29
45,670529,AEU Enact Demonstration Color,AEU Enact Demonstration Color,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670529/gunda...,2025-12-24T20:13:37.257,1,True,...,2,1,2026-01-29,0.25,0.50,1.00,0.33,None,Normal,2026-01-29
46,670530,Paptimus Scirocco,Paptimus Scirocco,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670530/gunda...,2026-01-22T20:55:59.553,1,True,...,+2,+2,2026-01-29,2.32,6.50,20.32,2.55,None,Holofoil,2026-01-29
47,670531,Christina Mackenzie,Christina Mackenzie,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670531/gunda...,2025-12-24T20:13:53.813,1,True,...,+1,+1,2026-01-29,0.50,1.00,1.50,0.50,None,Normal,2026-01-29
48,670532,Yazan Gable,Yazan Gable,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670532/gunda...,2025-12-24T20:13:59.023,1,True,...,+1,+2,2026-01-29,0.25,0.33,0.40,0.25,None,Normal,2026-01-29
49,670533,Sarah Zabiarov,Sarah Zabiarov,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670533/gunda...,2025-12-24T20:14:05.527,1,True,...,+1,+1,2026-01-29,0.25,0.38,0.50,0.30,None,Normal,2026-01-29
50,670534,Bernard Wiseman,Bernard Wiseman,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670534/gunda...,2025-12-24T20:14:13.007,1,True,...,0,+1,2026-01-29,0.50,1.00,1.50,0.50,None,Normal,2026-01-29
51,670535,Nyaan,Nyaan,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670535/gunda...,2026-01-22T14:04:40.06,1,True,...,+1,+2,2026-01-29,0.50,1.50,2.00,0.50,None,Normal,2026-01-29
52,670536,Azee Gurumin,Azee Gurumin,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670536/gunda...,2025-12-24T20:14:23.47,1,True,...,+1,+2,2026-01-29,0.50,1.60,3.00,1.50,None,Normal,2026-01-29
53,670537,Jamil Neate,Jamil Neate,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670537/gunda...,2026-01-22T14:01:01.993,1,True,...,+2,+1,2026-01-29,0.25,0.38,0.50,0.29,None,Normal,2026-01-29
54,670538,Graham Aker,Graham Aker,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670538/gunda...,2026-01-22T13:53:00.453,1,True,...,+2,+1,2026-01-29,1.00,7.75,20.32,3.25,None,Holofoil,2026-01-29
55,670539,Bridge Crew,Bridge Crew,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670539/gunda...,2025-12-24T20:14:40.24,1,True,...,NaN,NaN,2026-01-29,0.32,5.50,20.32,1.00,None,Holofoil,2026-01-29
56,670540,Eliminate Target,Eliminate Target,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670540/gunda...,2026-01-22T13:50:37.78,1,True,...,NaN,NaN,2026-01-29,0.50,1.00,1.50,NaN,None,Normal,2026-01-29
57,670541,Warped Intent,Warped Intent,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670541/gunda...,2025-12-24T20:14:52.08,1,True,...,NaN,NaN,2026-01-29,0.25,0.38,0.50,0.40,None,Normal,2026-01-29
58,670542,Human Karma,Human Karma,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670542/gunda...,2026-01-22T13:59:14.06,1,True,...,NaN,NaN,2026-01-29,0.25,0.50,1.00,0.33,None,Normal,2026-01-29
59,670543,Look of Determination,Look of Determination,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670543/gunda...,2026-01-22T14:02:50.427,1,True,...,NaN,NaN,2026-01-29,2.50,8.25,20.32,5.33,None,Holofoil,2026-01-29
60,670544,Orga's Order,Orgas Order,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670544/gunda...,2026-01-22T14:04:44.277,1,True,...,NaN,NaN,2026-01-29,0.25,0.38,0.50,0.30,None,Normal,2026-01-29
61,670545,Awakened Potential,Awakened Potential,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670545/gunda...,2025-12-24T20:15:16.587,1,True,...,NaN,NaN,2026-01-29,0.32,6.75,20.32,NaN,None,Holofoil,2026-01-29
62,670546,Awkward Approach,Awkward Approach,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670546/gunda...,2025-12-24T20:15:22.35,1,True,...,NaN,NaN,2026-01-29,0.50,1.50,3.00,0.50,None,Normal,2026-01-29
63,670547,Immortal Colasour,Immortal Colasour,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670547/gunda...,2026-01-22T13:59:30.83,1,True,...,+1,0,2026-01-29,0.50,1.05,1.60,1.00,None,Normal,2026-01-29
64,670548,Unheralded Attack,Unheralded Attack,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670548/gunda...,2025-12-24T20:15:34.893,1,True,...,+1,0,2026-01-29,0.25,0.33,0.40,NaN,None,Normal,2026-01-29
65,670549,Cyclops Team,Cyclops Team,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670549/gunda...,2025-12-24T20:15:42.077,1,True,...,0,5,2026-01-29,0.25,0.40,1.00,NaN,None,Normal,2026-01-29
66,670550,Ad Balloon,Ad Balloon,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/670550/gunda...,2025-12-24T20:15:48.73,1,True,...,0,1,2026-01-29,5.00,23.01,25.00,NaN,None,Normal,2026-01-29
67,673452,Gundam NT-1 Full Armor,Gundam NT 1 Full Armor,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/673452/gunda...,2026-01-22T13:55:38.78,1,True,...,2,3,2026-01-29,0.50,1.50,3.00,NaN,None,Normal,2026-01-29
68,673453,Bolinoak Sammahn,Bolinoak Sammahn,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/673453/gunda...,2026-01-21T22:08:45.2,1,True,...,3,3,2026-01-29,0.50,1.60,3.00,1.00,None,Normal,2026-01-29
69,673454,Palace Athene,Palace Athene,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/673454/gunda...,2026-01-22T14:04:52.333,1,True,...,5,3,2026-01-29,0.50,1.50,2.00,0.50,None,Normal,2026-01-29
70,673455,Full Armor Unicorn Gundam (Destroy Mode),Full Armor Unicorn Gundam Destroy Mode,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/673455/gunda...,2026-01-22T13:51:09.41,1,True,...,6,6,2026-01-29,0.50,1.05,1.60,1.50,None,Normal,2026-01-29
71,673456,GM Sniper II,GM Sniper II,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/673456/gunda...,2026-01-22T13:52:30.55,1,True,...,2,3,2026-01-29,0.25,0.33,0.40,0.25,None,Normal,2026-01-29
72,673457,Messala (MA Mode),Messala MA Mode,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/673457/gunda...,2026-01-22T14:03:06.137,1,True,...,3,2,2026-01-29,0.25,0.50,1.00,0.33,None,Normal,2026-01-29
73,673458,Hizack,Hizack,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/673458/gunda...,2026-01-22T13:58:24.52,1,True,...,2,2,2026-01-29,0.25,0.33,0.40,0.25,None,Normal,2026-01-29
74,673459,Kampfer,Kampfer,https://tcgplayer-cdn.tcgplayer.com/product/67...,86,Steel Requiem (GD03),https://www.tcgplayer.com/product/673459/gunda...,2026-01-22T14:02:42.24,1,True,...,4,3,2026-01-29,13.01,32.00,75.00,13.67,None,Holofoil,2026-01-29

In [30]:
#Drop unncessary columns for exploration
df_copy = df.copy() #back-up
df.drop(columns=['productId',
                 'cleanName',
                 'categoryId',
                 'modifiedOn',
                 'isPresale',
                 'releasedOn',
                 'directLowPrice',
                 'imageCount',
                 'Date_y',
                 'Number',
                 'Description',
                 'Level',
                 'Cost',
                 'Trait',
                 'Link Condition',
                 'Attack Points',
                 'Hit Points'
                ]
        ,inplace=True)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1117 entries, 0 to 1116
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         1117 non-null   object
 1   imageUrl     1117 non-null   object
 2   Set          1117 non-null   object
 3   url          1117 non-null   object
 4   Rarity       1046 non-null   object
 5   CardType     1043 non-null   object
 6   Color        918 non-null    object
 7   Date         1117 non-null   object
 8   lowPrice     1045 non-null   float64
 9   midPrice     1045 non-null   float64
 10  highPrice    1045 non-null   float64
 11  marketPrice  1002 non-null   float64
 12  Holofoil     1045 non-null   object
dtypes: float64(4), object(9)
memory usage: 122.2+ KB

In [32]:
#Keep only card information
case_mask = ~df['name'].str.contains('Starter Deck|Display Case|Booster Box Case|Booster Pack|Booster Box')

In [33]:
df = df[case_mask]

In [34]:
#What is the most expensive card(s) currently listed at?
df[df['marketPrice'] == df['marketPrice'].max()]

,name,imageUrl,Set,url,Rarity,CardType,Color,Date,lowPrice,midPrice,highPrice,marketPrice,Holofoil
1046,Wing Gundam (LR+),https://tcgplayer-cdn.tcgplayer.com/product/61...,Edition Beta,https://www.tcgplayer.com/product/616611/gunda...,LR+,Unit,Green,2026-01-29,5000.0,5000.0,5000.0,3999.99,Holofoil

In [35]:
#What is the current average market price of cards per set?
df.groupby('Set')['marketPrice'].mean().round(2).sort_values(ascending=False)

Set
Edition Beta                                 161.16
Promotional EX Resource Tokens               105.26
Gundam Promotional Cards                      45.85
Promotional EX Base Tokens                    29.36
Promotional Resource Tokens                   25.07
Starter Deck 07: Celestial Drive (ST07)       12.33
Newtype Rising (GD01)                         10.25
Starter Deck 04: SEED Strike (ST04)           10.02
Starter Deck 08: Flash of Radiance (ST08)      9.62
Starter Deck 01: Heroic Beginnings (ST01)      8.82
Starter Deck 05: Iron Bloom (ST05)             8.61
Dual Impact (GD02)                             8.24
Starter Deck 03: Zeon's Rush (ST03)            8.21
Starter Deck 06: Clan Unity (ST06)             7.79
Starter Deck 02: Wings of Advance (ST02)       7.46
Steel Requiem (GD03)                           3.09
Name: marketPrice, dtype: float64

In [36]:
#What is the price gap between rarities?
df.groupby('Rarity')['marketPrice'].mean().round(2).sort_values(ascending=False)

Rarity
LR++           393.76
U+             349.52
LR+            176.89
R+              39.01
Promo           33.29
C++             29.47
Legend Rare     25.49
C+              20.49
Common           5.82
Rare             5.04
Uncommon         1.03
Name: marketPrice, dtype: float64

In [37]:
df[df['Rarity'] == 'LR++'].sort_values(by='marketPrice',ascending=False)

,name,imageUrl,Set,url,Rarity,CardType,Color,Date,lowPrice,midPrice,highPrice,marketPrice,Holofoil
727,Gundam (GD01-001) (LR++),https://tcgplayer-cdn.tcgplayer.com/product/64...,Newtype Rising (GD01),https://www.tcgplayer.com/product/645375/gunda...,LR++,Unit,Blue,2026-01-29,699.99,710.0,805.00,471.05,Holofoil
728,Gundam Aerial Rebuild (LR++),https://tcgplayer-cdn.tcgplayer.com/product/64...,Newtype Rising (GD01),https://www.tcgplayer.com/product/645376/gunda...,LR++,Unit,White,2026-01-29,428.99,504.0,999.00,427.73,Holofoil
372,Gundam Barbatos 1st Form (LR++),https://tcgplayer-cdn.tcgplayer.com/product/65...,Dual Impact (GD02),https://www.tcgplayer.com/product/659292/gunda...,LR++,Unit,Purple,2026-01-29,380.00,450.0,460.81,390.38,Holofoil
359,GQuuuuuuX (Omega Psycommu) (LR++),https://tcgplayer-cdn.tcgplayer.com/product/65...,Dual Impact (GD02),https://www.tcgplayer.com/product/659279/gunda...,LR++,Unit,Red,2026-01-29,269.90,310.0,499.99,285.89,Holofoil

In [38]:
#Price Gap between the LR++ (highest rarity) cards?
max_rarity_max_price = df[df['Rarity'] == 'LR++']['marketPrice'].max()
max_rarity_low_price = df[df['Rarity'] == 'LR++']['marketPrice'].min()
max_rarity_max_price - max_rarity_low_price

185.16000000000003

In [39]:
#What is the most expensive card by set?
set_max_card = df.groupby('Set')['marketPrice'].transform(max)
max_per_set = df.loc[df['marketPrice'] == set_max_card,['name','Set','Rarity','marketPrice','Holofoil']].sort_values(by='marketPrice',ascending=False)

In [40]:
max_per_set

,name,Set,Rarity,marketPrice,Holofoil
1046,Wing Gundam (LR+),Edition Beta,LR+,3999.99,Holofoil
919,Heero Yuy (Championship Finalist Card 01),Gundam Promotional Cards,Common,1600.00,Holofoil
727,Gundam (GD01-001) (LR++),Newtype Rising (GD01),LR++,471.05,Holofoil
372,Gundam Barbatos 1st Form (LR++),Dual Impact (GD02),LR++,390.38,Holofoil
1010,EX Resource (EXRP-003) (Mobile Suit Gundam the...,Promotional EX Resource Tokens,Promo,259.09,Holofoil
997,EX Base (EXBP-001) (Mobile Suit Gundam),Promotional EX Base Tokens,Promo,175.43,Holofoil
875,Aile Strike Gundam (LR+),Starter Deck 04: SEED Strike (ST04),LR+,99.32,Holofoil
234,Gundam Dynames (LR+),Starter Deck 07: Celestial Drive (ST07),LR+,80.34,Holofoil
758,Gundam (LR+),Starter Deck 01: Heroic Beginnings (ST01),LR+,79.52,Holofoil
836,Sinanju (LR+),Starter Deck 03: Zeon's Rush (ST03),LR+,75.36,Holofoil
797,Wing Gundam (LR+),Starter Deck 02: Wings of Advance (ST02),LR+,69.95,Holofoil
523,Gundam Barbatos 4th Form (LR+),Starter Deck 05: Iron Bloom (ST05),LR+,67.74,Holofoil
271,Penelope (LR+),Starter Deck 08: Flash of Radiance (ST08),LR+,60.39,Holofoil
475,GQuuuuuuX (Omega Psycommu) (LR+),Starter Deck 06: Clan Unity (ST06),LR+,44.65,Holofoil
1020,Resource (RP-014) (Char Aznable Emblem),Promotional Resource Tokens,Promo,42.13,Holofoil
13,Altron Gundam,Steel Requiem (GD03),Legend Rare,27.56,Holofoil

In [41]:
#What is the most expensive 'color' card by set?
green_df = df[df['Color'] == 'Green'][['name','Set','CardType','Color','marketPrice','Holofoil']]
white_df = df[df['Color'] == 'White'][['name','Set','CardType','Color','marketPrice','Holofoil']]
red_df = df[df['Color'] == 'Red'][['name','Set','CardType','Color','marketPrice','Holofoil']]
blue_df = df[df['Color'] == 'Blue'][['name','Set','CardType','Color','marketPrice','Holofoil']]
purple_df = df[df['Color'] == 'Purple'][['name','Set','CardType','Color','marketPrice','Holofoil']]

In [42]:
#Green
green_set_max = green_df.groupby('Set')['marketPrice'].transform(max)
green_df[green_df['marketPrice'] == green_set_max].sort_values(by='marketPrice',ascending=False)

,name,Set,CardType,Color,marketPrice,Holofoil
1046,Wing Gundam (LR+),Edition Beta,Unit,Green,3999.99,Holofoil
919,Heero Yuy (Championship Finalist Card 01),Gundam Promotional Cards,Pilot,Green,1600.00,Holofoil
234,Gundam Dynames (LR+),Starter Deck 07: Celestial Drive (ST07),Unit,Green,80.34,Holofoil
696,Wing Gundam Zero (LR+),Newtype Rising (GD01),Unit,Green,76.84,Holofoil
797,Wing Gundam (LR+),Starter Deck 02: Wings of Advance (ST02),Unit,Green,69.95,Holofoil
841,Char's Zaku II (LR+),Starter Deck 03: Zeon's Rush (ST03),Unit,Green,44.04,Holofoil
480,Red Gundam (LR+),Starter Deck 06: Clan Unity (ST06),Unit,Green,41.06,Holofoil
13,Altron Gundam,Steel Requiem (GD03),Unit,Green,27.56,Holofoil
405,Flit Asuno (R+),Dual Impact (GD02),Pilot,Green,25.21,Holofoil

In [43]:
green_df.sort_values(by='marketPrice',ascending=False)

,name,Set,CardType,Color,marketPrice,Holofoil
1046,Wing Gundam (LR+),Edition Beta,Unit,Green,3999.99,Holofoil
919,Heero Yuy (Championship Finalist Card 01),Gundam Promotional Cards,Pilot,Green,1600.00,Holofoil
1056,Char Aznable (C+),Edition Beta,Pilot,Green,595.11,Holofoil
1076,Char's Zaku II (R+),Edition Beta,Unit,Green,552.14,Holofoil
1101,First Contact (U+),Edition Beta,Command,Green,452.75,Normal
234,Gundam Dynames (LR+),Starter Deck 07: Celestial Drive (ST07),Unit,Green,80.34,Holofoil
696,Wing Gundam Zero (LR+),Newtype Rising (GD01),Unit,Green,76.84,Holofoil
797,Wing Gundam (LR+),Starter Deck 02: Wings of Advance (ST02),Unit,Green,69.95,Holofoil
930,Shenlong Gundam (GD01-029) (Judge Pack 01),Gundam Promotional Cards,Unit,Green,56.75,Holofoil
969,Gundam Deathscythe Hell (Store Tournament Winn...,Gundam Promotional Cards,Unit,Green,50.84,Holofoil
712,Shenlong Gundam (GD01-029) (R+),Newtype Rising (GD01),Unit,Green,46.06,Holofoil
841,Char's Zaku II (LR+),Starter Deck 03: Zeon's Rush (ST03),Unit,Green,44.04,Holofoil
480,Red Gundam (LR+),Starter Deck 06: Clan Unity (ST06),Unit,Green,41.06,Holofoil
922,Zaku II (Championship Participation Pack 01),Gundam Promotional Cards,Unit,Green,40.55,Holofoil
965,Tactical Visionary (Store Tournament Winner Pa...,Gundam Promotional Cards,Command,Green,39.30,Holofoil
719,Gundam Deathscythe (GD01-025) (LR+),Newtype Rising (GD01),Unit,Green,39.03,Holofoil
235,Lockon Stratos (Neil) (C+),Starter Deck 07: Celestial Drive (ST07),Pilot,Green,29.05,Holofoil
13,Altron Gundam,Steel Requiem (GD03),Unit,Green,27.56,Holofoil
405,Flit Asuno (R+),Dual Impact (GD02),Pilot,Green,25.21,Holofoil
75,Gundam AGE-2 Normal,Steel Requiem (GD03),Unit,Green,23.01,Holofoil
493,Schoolgirl and Smuggler (C+),Starter Deck 06: Clan Unity (ST06),Command,Green,22.93,Holofoil
718,Duo Maxwell (R+),Newtype Rising (GD01),Pilot,Green,21.96,Holofoil
846,Char Aznable (C+),Starter Deck 03: Zeon's Rush (ST03),Pilot,Green,20.33,Holofoil
843,Zaku II (C+),Starter Deck 03: Zeon's Rush (ST03),Unit,Green,19.73,Holofoil
343,Gundam AGE-1 Normal (LR+),Dual Impact (GD02),Unit,Green,19.59,Holofoil
806,Heero Yuy (C+),Starter Deck 02: Wings of Advance (ST02),Pilot,Green,19.40,Holofoil
346,Red Gundam (R+),Dual Impact (GD02),Unit,Green,18.30,Holofoil
937,Shuji Ito (Store Tournament Winner Pack 02),Gundam Promotional Cards,Pilot,Green,15.33,Holofoil
463,Gundam AGE-1 Spallow (R+),Dual Impact (GD02),Unit,Green,15.13,Holofoil
928,Fortress Defense (Championship Participation P...,Gundam Promotional Cards,Command,Green,15.07,Holofoil
232,Allelujah Haptism (C+),Starter Deck 07: Celestial Drive (ST07),Pilot,Green,14.75,Holofoil
418,AGE Device (R+),Dual Impact (GD02),Command,Green,14.55,Holofoil
229,Gundam Kyrios (ST07-007) (C+),Starter Deck 07: Celestial Drive (ST07),Unit,Green,14.20,Holofoil
74,Kampfer,Steel Requiem (GD03),Unit,Green,13.67,Holofoil
565,Wing Gundam Zero,Newtype Rising (GD01),Unit,Green,13.29,Holofoil
233,Tactical Visionary (C+),Starter Deck 07: Celestial Drive (ST07),Command,Green,13.20,Holofoil
486,Sugai's Gelgoog (GQ) (C+),Starter Deck 06: Clan Unity (ST06),Unit,Green,12.68,Holofoil
721,Char's Gelgoog (LR+),Newtype Rising (GD01),Unit,Green,12.13,Holofoil
902,Wing Gundam (Bird Mode) (Store Tournament Winn...,Gundam Promotional Cards,Unit,Green,12.02,Holofoil
230,Gundam Kyrios (Flight Mode) (C+),Starter Deck 07: Celestial Drive (ST07),Unit,Green,11.24,Holofoil
482,Red Gundam (C+),Starter Deck 06: Clan Unity (ST06),Unit,Green,10.57,Holofoil
228,Gundam Dynames (ST07-006) (C+),Starter Deck 07: Celestial Drive (ST07),Unit,Green,10.21,Holofoil
720,Big Zam (R+),Newtype Rising (GD01),Unit,Green,9.83,Holofoil
489,Shuji Ito (C+),Starter Deck 06: Clan Unity (ST06),Pilot,Green,9.50,Holofoil
941,Gundam AGE-1 Normal (Store Tournament Winner P...,Gundam Promotional Cards,Unit,Green,9.35,Holofoil
484,Ortega's Rick Dom (GQ) (C+),Starter Deck 06: Clan Unity (ST06),Unit,Green,8.89,Holofoil
499,"Kaneban Co., Ltd. (C+)",Starter Deck 06: Clan Unity (ST06),Base,Green,8.82,Holofoil
1045,Wing Gundam (ST02-001),Edition Beta,Unit,Green,8.00,Holofoil
798,Wing Gundam (Bird Mode) (C+),Starter Deck 02: Wings of Advance (ST02),Unit,Green,6.87,Holofoil
916,Duo Maxwell (Store Tournament Winner Pack 01),Gundam Promotional Cards,Pilot,Green,6.64,Holofoil
714,"Citizens, Take a Stand! (R+)",Newtype Rising (GD01),Command,Green,6.30,Holofoil
825,Char's Zaku II,Starter Deck 03: Zeon's Rush (ST03),Unit,Green,6.29,Holofoil
844,Gouf (C+),Starter Deck 03: Zeon's Rush (ST03),Unit,Green,6.04,Holofoil
342,Elmeth (LR+),Dual Impact (GD02),Unit,Green,5.83,Holofoil
495,Fierce Unity (C+),Starter Deck 06: Clan Unity (ST06),Command,Green,5.72,Holofoil
781,Wing Gundam,Starter Deck 02: Wings of Advance (ST02),Unit,Green,5.41,Holofoil
800,Gundam Sandrock (C+),Starter Deck 02: Wings of Advance (ST02),Unit,Green,5.01,Holofoil
811,Saint Gabriel Institute (C+),Starter Deck 02: Wings of Advance (ST02),Base,Green,4.99,Holofoil
799,Gundam Heavyarms (C+),Starter Deck 02: Wings of Advance (ST02),Unit,Green,4.72,Holofoil
808,Simultaneous Fire (C+),Starter Deck 02: Wings of Advance (ST02),Command,Green,4.68,Holofoil
15,Gundam Deathscythe Hell,Steel Requiem (GD03),Unit,Green,4.40,Holofoil
851,Falmel (C+),Starter Deck 03: Zeon's Rush (ST03),Base,Green,3.83,Holofoil
809,Peaceful Timbre (C+),Starter Deck 02: Wings of Advance (ST02),Command,Green,3.78,Holofoil
842,Zaku I (C+),Starter Deck 03: Zeon's Rush (ST03),Unit,Green,3.61,Holofoil
1054,Zaku II,Edition Beta,Unit,Green,3.58,Normal
949,White Wolf (Store Tournament Winner Pack 02),Gundam Promotional Cards,Pilot,Green,3.30,Holofoil
16,Gundam Kyrios,Steel Requiem (GD03),Unit,Green,3.25,Holofoil
964,Tactical Visionary (Store Tournament Participa...,Gundam Promotional Cards,Command,Green,3.23,Holofoil
470,Red Gundam,Starter Deck 06: Clan Unity (ST06),Unit,Green,3.01,Holofoil
570,Shenlong Gundam (GD01-029),Newtype Rising (GD01),Unit,Green,2.92,Holofoil
566,Gundam Deathscythe (GD01-025),Newtype Rising (GD01),Unit,Green,2.71,Holofoil
283,Gundam AGE-1 Normal,Dual Impact (GD02),Unit,Green,2.66,Holofoil
1080,Gundam Heavyarms,Edition Beta,Unit,Green,2.60,Normal
827,Zaku II,Starter Deck 03: Zeon's Rush (ST03),Unit,Green,2.59,Normal
1049,Heero Yuy,Edition Beta,Pilot,Green,2.52,Normal
968,Gundam Deathscythe Hell (Store Tournament Part...,Gundam Promotional Cards,Unit,Green,2.49,Holofoil
849,The Blue Giant (C+),Starter Deck 03: Zeon's Rush (ST03),Command,Green,2.42,Holofoil
801,Maganac (C+),Starter Deck 02: Wings of Advance (ST02),Unit,Green,2.37,Holofoil
14,Zaku II FZ,Steel Requiem (GD03),Unit,Green,2.32,Holofoil
1075,Char's Zaku II,Edition Beta,Unit,Green,1.83,Holofoil
935,Red Gundam (Boost Kit 01),Gundam Promotional Cards,Unit,Green,1.74,Holofoil
564,Char's Gelgoog,Newtype Rising (GD01),Unit,Green,1.64,Holofoil
309,Elmeth,Dual Impact (GD02),Unit,Green,1.57,Holofoil
18,Gundam Sandrock Custom,Steel Requiem (GD03),Unit,Green,1.50,Normal
218,Gundam Dynames (LR),Starter Deck 07: Celestial Drive (ST07),Unit,Green,1.38,Holofoil
130,Peacemillion,Steel Requiem (GD03),Base,Green,1.25,Normal
1055,Char Aznable,Edition Beta,Pilot,Green,1.11,Normal
1077,Gundam Sandrock,Edition Beta,Unit,Green,1.08,Holofoil
108,Asemu Asuno,Steel Requiem (GD03),Pilot,Green,1.00,Holofoil
17,G-Bouncer,Steel Requiem (GD03),Unit,Green,1.00,Holofoil
55,Bridge Crew,Steel Requiem (GD03),Command,Green,1.00,Holofoil
936,Shuji Ito (Store Tournament Participant Pack 02),Gundam Promotional Cards,Pilot,Green,0.96,Holofoil
1099,"Citizens, Take a Stand!",Edition Beta,Command,Green,0.95,Holofoil
1078,Rick Dom,Edition Beta,Unit,Green,0.89,Normal
1094,Chang Wufei,Edition Beta,Pilot,Green,0.86,Normal
1082,Shenlong Gundam,Edition Beta,Unit,Green,0.86,Normal
790,Heero Yuy,Starter Deck 02: Wings of Advance (ST02),Pilot,Green,0.81,Normal
901,Wing Gundam (Bird Mode) (Store Tournament Part...,Gundam Promotional Cards,Unit,Green,0.77,Holofoil
77,Gundam Dynames,Steel Requiem (GD03),Unit,Green,0.70,Normal
345,Red Gundam,Dual Impact (GD02),Unit,Green,0.59,Holofoil
915,Duo Maxwell (Store Tournament Participant Pack...,Gundam Promotional Cards,Pilot,Green,0.58,Holofoil
631,Duo Maxwell,Newtype Rising (GD01),Pilot,Green,0.56,Holofoil
50,Bernard Wiseman,Steel Requiem (GD03),Pilot,Green,0.50,Normal
121,Over the River and Through the Woods,Steel Requiem (GD03),Command,Green,0.50,Normal
1053,Zaku I,Edition Beta,Unit,Green,0.49,Normal
1052,Saint Gabriel Institute,Edition Beta,Base,Green,0.48,Normal
1081,Wing Gundam,Edition Beta,Unit,Green,0.48,Normal
830,Char Aznable,Starter Deck 03: Zeon's Rush (ST03),Pilot,Green,0.48,Normal
955,Flit Asuno (GD02 Release Event),Gundam Promotional Cards,Pilot,Green,0.46,Holofoil
1047,Wing Gundam (Bird Mode),Edition Beta,Unit,Green,0.41,Normal
1100,First Contact,Edition Beta,Command,Green,0.40,Normal
79,Gundam Heavyarms Custom,Steel Requiem (GD03),Unit,Green,0.40,Normal
1079,Gelgoog,Edition Beta,Unit,Green,0.39,Normal
954,Gundam AGE-1 Normal (GD02-029) (GD02 Release E...,Gundam Promotional Cards,Unit,Green,0.37,Holofoil
940,Gundam AGE-1 Normal (Store Tournament Particip...,Gundam Promotional Cards,Unit,Green,0.35,Holofoil
498,"Kaneban Co., Ltd.",Starter Deck 06: Clan Unity (ST06),Base,Green,0.35,Normal
568,Big Zam,Newtype Rising (GD01),Unit,Green,0.34,Holofoil
212,Gundam Dynames (ST07-006),Starter Deck 07: Celestial Drive (ST07),Unit,Green,0.33,Normal
948,White Wolf (Store Tournament Participant Pack 02),Gundam Promotional Cards,Pilot,Green,0.32,Holofoil
1057,Falmel,Edition Beta,Base,Green,0.31,Normal
567,Char's Zaku II,Newtype Rising (GD01),Unit,Green,0.30,Holofoil
646,"Citizens, Take a Stand!",Newtype Rising (GD01),Command,Green,0.29,Holofoil
833,The Blue Giant,Starter Deck 03: Zeon's Rush (ST03),Command,Green,0.29,Normal
494,Fierce Unity,Starter Deck 06: Clan Unity (ST06),Command,Green,0.28,Normal
1048,Maganac,Edition Beta,Unit,Green,0.27,Normal
573,Gyan,Newtype Rising (GD01),Unit,Green,0.26,Holofoil
217,Tactical Visionary,Starter Deck 07: Celestial Drive (ST07),Command,Green,0.26,Normal
214,Gundam Kyrios (Flight Mode),Starter Deck 07: Celestial Drive (ST07),Unit,Green,0.25,Normal
21,Gundam AGE-1 Flat,Steel Requiem (GD03),Unit,Green,0.25,Normal
109,Mikhail Kaminsky,Steel Requiem (GD03),Pilot,Green,0.25,Normal
80,Zaku (Four Snake Eyes') [YETI] (GQ),Steel Requiem (GD03),Unit,Green,0.25,Normal
78,Z'Gok E,Steel Requiem (GD03),Unit,Green,0.25,Normal
122,How Many Miles to the Battlefield?,Steel Requiem (GD03),Command,Green,0.25,Normal
20,Gundam Kyrios (Tail Unit Flight Mode),Steel Requiem (GD03),Unit,Green,0.25,Normal
647,Fortress Defense,Newtype Rising (GD01),Command,Green,0.24,Holofoil
306,G-Exes,Dual Impact (GD02),Unit,Green,0.24,Holofoil
835,Falmel,Starter Deck 03: Zeon's Rush (ST03),Base,Green,0.23,Normal
1051,Peaceful Timbre,Edition Beta,Command,Green,0.22,Normal
314,Flit Asuno,Dual Impact (GD02),Pilot,Green,0.22,Holofoil
417,AGE Device,Dual Impact (GD02),Command,Green,0.22,Holofoil
571,Rick Dom,Newtype Rising (GD01),Unit,Green,0.22,Normal
213,Gundam Kyrios (ST07-007),Starter Deck 07: Celestial Drive (ST07),Unit,Green,0.21,Normal
826,Zaku I,Starter Deck 03: Zeon's Rush (ST03),Unit,Green,0.21,Normal
1050,Simultaneous Fire,Edition Beta,Command,Green,0.21,Normal
569,Gundam Sandrock,Newtype Rising (GD01),Unit,Green,0.21,Holofoil
216,Allelujah Haptism,Starter Deck 07: Celestial Drive (ST07),Pilot,Green,0.19,Normal
792,Simultaneous Fire,Starter Deck 02: Wings of Advance (ST02),Command,Green,0.19,Normal
481,Red Gundam (C),Starter Deck 06: Clan Unity (ST06),Unit,Green,0.19,Normal
576,Zaku II,Newtype Rising (GD01),Unit,Green,0.19,Normal
219,Lockon Stratos (Neil),Starter Deck 07: Celestial Drive (ST07),Pilot,Green,0.19,Normal
492,Schoolgirl and Smuggler,Starter Deck 06: Clan Unity (ST06),Command,Green,0.19,Normal
828,Gouf,Starter Deck 03: Zeon's Rush (ST03),Unit,Green,0.18,Normal
485,Sugai's Gelgoog (GQ),Starter Deck 06: Clan Unity (ST06),Unit,Green,0.18,Normal
782,Wing Gundam (Bird Mode),Starter Deck 02: Wings of Advance (ST02),Unit,Green,0.17,Normal
783,Gundam Heavyarms,Starter Deck 02: Wings of Advance (ST02),Unit,Green,0.17,Normal
795,Saint Gabriel Institute,Starter Deck 02: Wings of Advance (ST02),Base,Green,0.17,Normal
433,Sodon,Dual Impact (GD02),Base,Green,0.17,Holofoil
667,Underground Desert Base,Newtype Rising (GD01),Base,Green,0.16,Normal
784,Gundam Sandrock,Starter Deck 02: Wings of Advance (ST02),Unit,Green,0.16,Normal
471,Shuji Ito,Starter Deck 06: Clan Unity (ST06),Pilot,Green,0.16,Normal
483,Ortega's Rick Dom (GQ),Starter Deck 06: Clan Unity (ST06),Unit,Green,0.15,Normal
632,Chang Wufei,Newtype Rising (GD01),Pilot,Green,0.15,Normal
280,Gundam Heavyarms,Dual Impact (GD02),Unit,Green,0.13,Normal
793,Peaceful Timbre,Starter Deck 02: Wings of Advance (ST02),Command,Green,0.13,Normal
287,Turning Point of History,Dual Impact (GD02),Command,Green,0.13,Normal
648,First Contact,Newtype Rising (GD01),Command,Green,0.12,Normal
419,Valedictorian,Dual Impact (GD02),Command,Green,0.12,Normal
650,The Path to Victory or Defeat,Newtype Rising (GD01),Command,Green,0.12,Normal
582,Shenlong Gundam (GD01-041),Newtype Rising (GD01),Unit,Green,0.12,Normal
785,Maganac,Starter Deck 02: Wings of Advance (ST02),Unit,Green,0.11,Normal
315,Lalah Sune,Dual Impact (GD02),Pilot,Green,0.11,Normal
666,Zanzibar,Newtype Rising (GD01),Base,Green,0.11,Normal
574,Gundam Deathscythe (GD01-033),Newtype Rising (GD01),Unit,Green,0.11,Normal
572,Gelgoog,Newtype Rising (GD01),Unit,Green,0.10,Normal
584,Rasid's Maganac,Newtype Rising (GD01),Unit,Green,0.10,Normal
575,Gundam Heavyarms,Newtype Rising (GD01),Unit,Green,0.10,Normal
344,Gundam AGE-1 Spallow,Dual Impact (GD02),Unit,Green,0.09,Holofoil
580,Dopp,Newtype Rising (GD01),Unit,Green,0.09,Normal
310,Gundam AGE-1 Normal (GD02-029),Dual Impact (GD02),Unit,Green,0.09,Normal
292,Police Zaku (Armored RRU Type),Dual Impact (GD02),Unit,Green,0.09,Normal
351,Kikeroga (MA Mode) (GQ),Dual Impact (GD02),Unit,Green,0.08,Normal
300,Challia Bull (GQ),Dual Impact (GD02),Pilot,Green,0.08,Normal
291,Gundam AGE-1 Titus,Dual Impact (GD02),Unit,Green,0.08,Normal
290,Abdul's Maganac,Dual Impact (GD02),Unit,Green,0.08,Normal
350,White Gundam,Dual Impact (GD02),Unit,Green,0.08,Normal
581,Wing Gundam (GD01-040),Newtype Rising (GD01),Unit,Green,0.08,Normal
352,GQuuuuuuX,Dual Impact (GD02),Unit,Green,0.08,Normal
577,Gouf,Newtype Rising (GD01),Unit,Green,0.08,Normal
583,Duo's Leo,Newtype Rising (GD01),Unit,Green,0.08,Normal
651,Rasid's Orders,Newtype Rising (GD01),Command,Green,0.08,Normal
578,Gogg,Newtype Rising (GD01),Unit,Green,0.07,Normal
633,M'Quve,Newtype Rising (GD01),Pilot,Green,0.07,Normal
349,Genoace,Dual Impact (GD02),Unit,Green,0.06,Normal
347,Genoace Custom,Dual Impact (GD02),Unit,Green,0.06,Normal
319,White Wolf,Dual Impact (GD02),Pilot,Green,0.06,Normal
434,Diva,Dual Impact (GD02),Base,Green,0.06,Normal
348,Gundam AGE-1 Titus (GD02-027),Dual Impact (GD02),Unit,Green,0.05,Normal
579,Adzam,Newtype Rising (GD01),Unit,Green,0.05,Normal
649,Strategic Arms,Newtype Rising (GD01),Command,Green,0.05,Normal
19,Auda's Maganac,Steel Requiem (GD03),Unit,Green,NaN,Normal
65,Cyclops Team,Steel Requiem (GD03),Base,Green,NaN,Normal
76,Hy-Gogg,Steel Requiem (GD03),Unit,Green,NaN,Normal
120,M.A.V. Tactics,Steel Requiem (GD03),Command,Green,NaN,Normal
156,Altron Gundam (LR+),Steel Requiem (GD03),Unit,Green,NaN,NaN
157,Asemu Asuno (R+),Steel Requiem (GD03),Pilot,Green,NaN,NaN
160,Bridge Crew (R+),Steel Requiem (GD03),Command,Green,NaN,NaN
162,First Contact (SP) (U+),Steel Requiem (GD03),Command,Green,NaN,NaN
170,Gundam AGE-2 Normal (LR+),Steel Requiem (GD03),Unit,Green,NaN,NaN
174,Gundam Kyrios (R+),Steel Requiem (GD03),Unit,Green,NaN,NaN
178,Kampfer (LR+),Steel Requiem (GD03),Unit,Green,NaN,NaN
179,Kampfer (LR++),Steel Requiem (GD03),Unit,Green,NaN,NaN
199,Zaku II FZ (R+),Steel Requiem (GD03),Unit,Green,NaN,NaN
920,Wing Gundam Zero (Championship Winner Card 01),Gundam Promotional Cards,Unit,Green,NaN,Holofoil
980,Zaku II (Premium Card Collection),Gundam Promotional Cards,Unit,Green,NaN,NaN

In [44]:
#White
white_set_max = white_df.groupby('Set')['marketPrice'].transform(max)
white_df[white_df['marketPrice'] == white_set_max].sort_values(by='marketPrice',ascending=False)

,name,Set,CardType,Color,marketPrice,Holofoil
1104,Overflowing Affection (U+),Edition Beta,Command,White,2385.97,Holofoil
728,Gundam Aerial Rebuild (LR++),Newtype Rising (GD01),Unit,White,427.73,Holofoil
910,Gundam Aerial Rebuild (Newtype Challenge 2025 ...,Gundam Promotional Cards,Unit,White,328.16,Holofoil
875,Aile Strike Gundam (LR+),Starter Deck 04: SEED Strike (ST04),Unit,White,99.32,Holofoil
766,Zowort (C+),Starter Deck 01: Heroic Beginnings (ST01),Unit,White,28.95,Holofoil
36,Graham's Union Flag Custom,Steel Requiem (GD03),Unit,White,26.84,Holofoil
387,Zeta Gundam (LR+),Dual Impact (GD02),Unit,White,22.50,Holofoil
529,McGillis' Schwalbe Graze (LR+),Starter Deck 05: Iron Bloom (ST05),Unit,White,16.14,Holofoil

In [45]:
#Red
red_set_max = red_df.groupby('Set')['marketPrice'].transform(max)
red_df[red_df['marketPrice'] == red_set_max].sort_values(by='marketPrice',ascending=False)

,name,Set,CardType,Color,marketPrice,Holofoil
959,Qubeley (Newtype Challenge 2025 Mission 3),Gundam Promotional Cards,Unit,Red,360.64,Holofoil
359,GQuuuuuuX (Omega Psycommu) (LR++),Dual Impact (GD02),Unit,Red,285.89,Holofoil
836,Sinanju (LR+),Starter Deck 03: Zeon's Rush (ST03),Unit,Red,75.36,Holofoil
715,Marida Cruz (R+),Newtype Rising (GD01),Pilot,Red,67.28,Holofoil
259,Xi Gundam (ST08-001) (LR+),Starter Deck 08: Flash of Radiance (ST08),Unit,Red,54.68,Holofoil
475,GQuuuuuuX (Omega Psycommu) (LR+),Starter Deck 06: Clan Unity (ST06),Unit,Red,44.65,Holofoil
880,Aegis Gundam (LR+),Starter Deck 04: SEED Strike (ST04),Unit,Red,36.76,Holofoil
81,Providence Gundam,Steel Requiem (GD03),Unit,Red,24.01,Holofoil

In [46]:
#Blue
blue_set_max = blue_df.groupby('Set')['marketPrice'].transform(max)
blue_df[blue_df['marketPrice'] == blue_set_max].sort_values(by='marketPrice',ascending=False)

,name,Set,CardType,Color,marketPrice,Holofoil
1033,Gundam (LR+),Edition Beta,Unit,Blue,1090.26,Holofoil
727,Gundam (GD01-001) (LR++),Newtype Rising (GD01),Unit,Blue,471.05,Holofoil
758,Gundam (LR+),Starter Deck 01: Heroic Beginnings (ST01),Unit,Blue,79.52,Holofoil
328,Gundam Epyon (LR+),Dual Impact (GD02),Unit,Blue,72.87,Holofoil
271,Penelope (LR+),Starter Deck 08: Flash of Radiance (ST08),Unit,Blue,60.39,Holofoil
924,Guntank (Championship Participation Pack 01),Gundam Promotional Cards,Unit,Blue,53.84,Holofoil
802,Tallgeese (LR+),Starter Deck 02: Wings of Advance (ST02),Unit,Blue,34.29,Holofoil
5,The-O,Steel Requiem (GD03),Unit,Blue,24.00,Holofoil

In [47]:
#Purple
purple_set_max = purple_df.groupby('Set')['marketPrice'].transform(max)
purple_df[purple_df['marketPrice'] == purple_set_max].sort_values(by='marketPrice',ascending=False)

,name,Set,CardType,Color,marketPrice,Holofoil
372,Gundam Barbatos 1st Form (LR++),Dual Impact (GD02),Unit,Purple,390.38,Holofoil
224,Gundam Exia (ST07-001) (LR+),Starter Deck 07: Celestial Drive (ST07),Unit,Purple,80.20,Holofoil
523,Gundam Barbatos 4th Form (LR+),Starter Deck 05: Iron Bloom (ST05),Unit,Purple,67.74,Holofoil
981,Gundam Barbatos 2nd Form (Premium Card Collect...,Gundam Promotional Cards,Unit,Purple,45.00,Holofoil
29,Gundam Exia (Trans-Am),Steel Requiem (GD03),Unit,Purple,27.45,Holofoil

In [50]:
df[df['Set'].str.contains('Steel Requiem')].sort_values(by='marketPrice',ascending=False)

,name,imageUrl,Set,url,Rarity,CardType,Color,Date,lowPrice,midPrice,highPrice,marketPrice,Holofoil
13,Altron Gundam,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670497/gunda...,Legend Rare,Unit,Green,2026-01-29,23.68,33.00,35.00,27.56,Holofoil
29,Gundam Exia (Trans-Am),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670513/gunda...,Legend Rare,Unit,Purple,2026-01-29,34.67,35.50,50.00,27.45,Holofoil
36,Graham's Union Flag Custom,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670520/gunda...,Legend Rare,Unit,White,2026-01-29,15.01,44.99,90.99,26.84,Holofoil
81,Providence Gundam,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673466/gunda...,Legend Rare,Unit,Red,2026-01-29,20.00,37.00,90.99,24.01,Holofoil
5,The-O,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670489/gunda...,Legend Rare,Unit,Blue,2026-01-29,20.00,25.00,90.99,24.00,Holofoil
37,Freedom Gundam (GD03-070),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670521/gunda...,Legend Rare,Unit,White,2026-01-29,23.68,39.99,50.00,23.94,Holofoil
75,Gundam AGE-2 Normal,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673460/gunda...,Legend Rare,Unit,Green,2026-01-29,20.00,25.00,90.99,23.01,Holofoil
30,Gundam Barbatos Lupus,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670514/gunda...,Legend Rare,Unit,Purple,2026-01-29,16.68,24.95,35.00,19.62,Holofoil
4,Gundam NT-1,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670488/gunda...,Legend Rare,Unit,Blue,2026-01-29,18.65,20.00,30.00,18.12,Holofoil
82,GQuuuuuuX (Omega Psycommu),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673467/gunda...,Legend Rare,Unit,Red,2026-01-29,13.68,39.47,65.00,14.47,Holofoil
22,GFreD,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670506/gunda...,Legend Rare,Unit,Red,2026-01-29,13.68,44.45,90.99,14.34,Holofoil
74,Kampfer,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673459/gunda...,Legend Rare,Unit,Green,2026-01-29,13.01,32.00,75.00,13.67,Holofoil
92,Gundam Gusion Rebake Full City,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673477/gunda...,Rare,Unit,Purple,2026-01-29,2.50,6.50,21.00,6.50,Holofoil
59,Look of Determination,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670543/gunda...,Rare,Command,Purple,2026-01-29,2.50,8.25,20.32,5.33,Holofoil
15,Gundam Deathscythe Hell,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670499/gunda...,Rare,Unit,Green,2026-01-29,2.50,10.00,20.32,4.40,Holofoil
95,Gundam Barbatos Adapt,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673480/gunda...,Rare,Unit,Purple,2026-01-29,3.00,4.75,21.00,4.00,Holofoil
16,Gundam Kyrios,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670500/gunda...,Rare,Unit,Green,2026-01-29,1.00,10.00,20.32,3.25,Holofoil
54,Graham Aker,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670538/gunda...,Rare,Pilot,White,2026-01-29,1.00,7.75,20.32,3.25,Holofoil
110,Rau Le Creuset,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673495/gunda...,Rare,Pilot,Red,2026-01-29,2.00,3.00,20.32,3.00,Holofoil
112,Zeheart Galette,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673497/gunda...,Rare,Pilot,Purple,2026-01-29,2.32,6.50,21.00,3.00,Holofoil
46,Paptimus Scirocco,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670530/gunda...,Rare,Pilot,Blue,2026-01-29,2.32,6.50,20.32,2.55,Holofoil
23,Xi Gundam (Flight Form),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670507/gunda...,Rare,Unit,Red,2026-01-29,2.32,6.50,20.32,2.32,Holofoil
14,Zaku II FZ,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670498/gunda...,Rare,Unit,Green,2026-01-29,2.32,3.50,20.32,2.32,Holofoil
123,Improved Technique,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673508/gunda...,Rare,Command,Red,2026-01-29,2.34,10.00,21.00,2.20,Holofoil
148,CGS Mobile Worker,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673533/gunda...,Common,Unit,NaN,2026-01-29,2.00,2.00,2.00,2.00,Normal
149,Graze Custom,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673534/gunda...,Common,Unit,NaN,2026-01-29,2.00,2.00,2.00,2.00,Normal
150,Gundam Barbatos 4th Form,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673535/gunda...,Common,Unit,NaN,2026-01-29,2.00,2.00,2.00,2.00,Normal
153,GFreD (T-020),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673538/gunda...,Common,Unit,NaN,2026-01-29,2.00,2.00,2.00,2.00,Normal
91,Gundam Virtue,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673476/gunda...,Rare,Unit,Purple,2026-01-29,1.00,3.50,21.00,1.83,Holofoil
90,Gundam X Divider,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673475/gunda...,Rare,Unit,Purple,2026-01-29,1.00,3.50,21.00,1.63,Holofoil
18,Gundam Sandrock Custom,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670502/gunda...,Uncommon,Unit,Green,2026-01-29,0.50,1.05,1.60,1.50,Normal
33,Gundam Barbatos 6th Form,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670517/gunda...,Uncommon,Unit,Purple,2026-01-29,0.50,1.05,1.60,1.50,Normal
32,CGS Mobile Worker (Commander Type),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670516/gunda...,Uncommon,Unit,Purple,2026-01-29,0.50,1.05,1.60,1.50,Normal
52,Azee Gurumin,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670536/gunda...,Uncommon,Pilot,Purple,2026-01-29,0.50,1.60,3.00,1.50,Normal
70,Full Armor Unicorn Gundam (Destroy Mode),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673455/gunda...,Uncommon,Unit,Blue,2026-01-29,0.50,1.05,1.60,1.50,Normal
7,Hambrabi,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670491/gunda...,Rare,Unit,Blue,2026-01-29,1.32,3.50,8.00,1.32,Holofoil
130,Peacemillion,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673515/gunda...,Uncommon,Base,Green,2026-01-29,0.50,1.75,3.00,1.25,Normal
108,Asemu Asuno,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673493/gunda...,Rare,Pilot,Green,2026-01-29,1.00,6.75,21.00,1.00,Holofoil
105,Justice Gundam (METEOR),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673490/gunda...,Uncommon,Unit,White,2026-01-29,0.50,1.05,1.60,1.00,Normal
94,Gundam Hajiroboshi (2nd Form),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673479/gunda...,Rare,Unit,Purple,2026-01-29,1.00,1.00,21.00,1.00,Holofoil
68,Bolinoak Sammahn,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673453/gunda...,Uncommon,Unit,Blue,2026-01-29,0.50,1.60,3.00,1.00,Normal
93,Zeydra,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673478/gunda...,Rare,Unit,Purple,2026-01-29,0.32,5.50,21.00,1.00,Holofoil
17,G-Bouncer,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670501/gunda...,Rare,Unit,Green,2026-01-29,1.00,5.50,20.32,1.00,Holofoil
84,GuAIZ (Commander Type),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673469/gunda...,Rare,Unit,Red,2026-01-29,0.32,5.50,21.00,1.00,Holofoil
24,Red Gundam,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670508/gunda...,Rare,Unit,Red,2026-01-29,1.00,5.50,20.32,1.00,Holofoil
116,A Healthy Curiosity,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673501/gunda...,Rare,Command,Blue,2026-01-29,1.00,5.00,8.00,1.00,Holofoil
8,Kshatriya Besserung,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670492/gunda...,Rare,Unit,Blue,2026-01-29,1.00,5.50,20.32,1.00,Holofoil
133,Hotarubi,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673518/gunda...,Uncommon,Base,Purple,2026-01-29,0.50,1.60,3.00,1.00,Normal
63,Immortal Colasour,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670547/gunda...,Uncommon,Command,White,2026-01-29,0.50,1.05,1.60,1.00,Normal
39,Tieren Taozi,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670523/gunda...,Rare,Unit,White,2026-01-29,0.32,5.50,20.32,1.00,Holofoil
55,Bridge Crew,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670539/gunda...,Rare,Command,Green,2026-01-29,0.32,5.50,20.32,1.00,Holofoil
40,Super Gundam,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670524/gunda...,Uncommon,Unit,White,2026-01-29,0.50,1.05,1.60,1.00,Normal
119,Reccoa's Shadow,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673504/gunda...,Uncommon,Command,Blue,2026-01-29,0.50,1.05,1.60,0.83,Normal
96,GN Armor (Type-E),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673481/gunda...,Uncommon,Unit,Purple,2026-01-29,0.50,1.05,1.60,0.80,Normal
77,Gundam Dynames,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673462/gunda...,Uncommon,Unit,Green,2026-01-29,1.60,2.30,3.00,0.70,Normal
103,Z Gundam (Biosensor),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673488/gunda...,Rare,Unit,White,2026-01-29,0.32,5.50,20.32,0.66,Holofoil
137,Resource (R-020),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673522/gunda...,Common,Resource,NaN,2026-01-29,0.25,0.38,0.50,0.50,Normal
139,Resource (R-022),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673524/gunda...,Common,Resource,NaN,2026-01-29,0.25,0.38,0.50,0.50,Normal
140,Resource (R-023),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673525/gunda...,Common,Resource,NaN,2026-01-29,0.25,0.25,0.25,0.50,Normal
141,Resource (R-024),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673526/gunda...,Common,Resource,NaN,2026-01-29,0.25,0.38,0.50,0.50,Normal
142,Resource (R-025),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673527/gunda...,Common,Resource,NaN,2026-01-29,0.25,0.38,0.50,0.50,Normal
51,Nyaan,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670535/gunda...,Uncommon,Pilot,Red,2026-01-29,0.50,1.50,2.00,0.50,Normal
47,Christina Mackenzie,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670531/gunda...,Uncommon,Pilot,Blue,2026-01-29,0.50,1.00,1.50,0.50,Normal
114,Emma Sheen,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673499/gunda...,Uncommon,Pilot,White,2026-01-29,0.50,1.00,1.50,0.50,Normal
69,Palace Athene,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673454/gunda...,Uncommon,Unit,Blue,2026-01-29,0.50,1.50,2.00,0.50,Normal
144,Resource (R-027),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673529/gunda...,Common,Resource,NaN,2026-01-29,0.25,0.38,0.50,0.50,Normal
50,Bernard Wiseman,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670534/gunda...,Uncommon,Pilot,Green,2026-01-29,0.50,1.00,1.50,0.50,Normal
42,Tieren High Mobility Type,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670526/gunda...,Uncommon,Unit,White,2026-01-29,0.50,1.00,1.50,0.50,Normal
118,Field Directive,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673503/gunda...,Uncommon,Command,Blue,2026-01-29,0.50,1.00,1.50,0.50,Normal
31,Zedas R,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670515/gunda...,Uncommon,Unit,Purple,2026-01-29,0.50,1.00,1.50,0.50,Normal
121,Over the River and Through the Woods,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673506/gunda...,Uncommon,Command,Green,2026-01-29,0.50,1.50,2.00,0.50,Normal
146,Resource (R-029),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673531/gunda...,Common,Resource,NaN,2026-01-29,0.25,0.38,0.50,0.50,Normal
138,Resource (R-021),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673523/gunda...,Common,Resource,NaN,2026-01-29,0.25,0.38,0.50,0.50,Normal
131,Jachin Due,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673516/gunda...,Uncommon,Base,Red,2026-01-29,0.50,1.50,2.00,0.50,Normal
62,Awkward Approach,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670546/gunda...,Uncommon,Command,White,2026-01-29,0.50,1.50,3.00,0.50,Normal
145,Resource (R-028),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673530/gunda...,Common,Resource,NaN,2026-01-29,0.25,0.38,0.50,0.50,Normal
111,Carris Nautilus,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673496/gunda...,Common,Pilot,Red,2026-01-29,0.25,0.38,0.50,0.40,Normal
12,Full Armor Unicorn Gundam (Unicorn Mode),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670496/gunda...,Common,Unit,Blue,2026-01-29,0.25,0.38,0.50,0.40,Normal
101,Gundam Barbatos 5th Form (Ground Type),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673486/gunda...,Common,Unit,Purple,2026-01-29,0.25,0.38,0.50,0.40,Normal
57,Warped Intent,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670541/gunda...,Common,Command,Red,2026-01-29,0.25,0.38,0.50,0.40,Normal
79,Gundam Heavyarms Custom,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673464/gunda...,Common,Unit,Green,2026-01-29,0.25,0.50,1.00,0.40,Normal
143,Resource (R-026),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673528/gunda...,Common,Resource,NaN,2026-01-29,0.25,0.38,0.50,0.38,Normal
107,AEU Hellion,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673492/gunda...,Common,Unit,White,2026-01-29,0.25,0.50,1.00,0.33,Normal
72,Messala (MA Mode),https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673457/gunda...,Common,Unit,Blue,2026-01-29,0.25,0.50,1.00,0.33,Normal
45,AEU Enact Demonstration Color,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670529/gunda...,Common,Unit,White,2026-01-29,0.25,0.50,1.00,0.33,Normal
129,Ribo Colony,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673514/gunda...,Common,Base,Blue,2026-01-29,0.25,0.38,0.50,0.33,Normal
127,Veteran Tactics,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673512/gunda...,Common,Command,White,2026-01-29,0.25,0.38,0.50,0.33,Normal
115,Soma Peries,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673500/gunda...,Common,Pilot,White,2026-01-29,0.25,0.38,0.50,0.33,Normal
106,Union Flag,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673491/gunda...,Common,Unit,White,2026-01-29,0.25,0.38,0.50,0.33,Normal
58,Human Karma,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670542/gunda...,Common,Command,Red,2026-01-29,0.25,0.50,1.00,0.33,Normal
35,Rouei,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670519/gunda...,Common,Unit,Purple,2026-01-29,0.25,0.38,0.50,0.33,Normal
104,Graze Ein,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673489/gunda...,Rare,Unit,White,2026-01-29,0.32,5.50,20.32,0.32,Holofoil
6,Messala,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670490/gunda...,Rare,Unit,Blue,2026-01-29,0.32,5.50,50.32,0.32,Holofoil
128,Jupitris,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673513/gunda...,Rare,Base,Blue,2026-01-29,0.32,5.50,20.32,0.32,Holofoil
60,Orga's Order,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670544/gunda...,Common,Command,Purple,2026-01-29,0.25,0.38,0.50,0.30,Normal
43,G-Defenser,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670527/gunda...,Common,Unit,White,2026-01-29,0.25,0.38,0.50,0.30,Normal
113,Wistario Afam,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673498/gunda...,Common,Pilot,Purple,2026-01-29,0.25,0.38,0.50,0.30,Normal
102,Gundam Hajiroboshi,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/673487/gunda...,Common,Unit,Purple,2026-01-29,0.25,0.38,0.50,0.30,Normal
49,Sarah Zabiarov,https://tcgplayer-cdn.tcgplayer.com/product/67...,Steel Requiem (GD03),https://www.tcgplayer.com/product/670533/gunda...,Common,Pilot,Blue,2026-01-29,0.25,0.38,0.50,0.30,Normal